# Label CafeF 2023 With DeepSeek V4 Flash

Notebook này đọc 1.000 dòng đầu từ `data/raw/cafef_raw/cafef_news_2023.csv`, nạp `system_prompt.txt` và `few_shots.txt`, rồi gọi DeepSeek Chat Completions để trích xuất sự kiện tài chính theo schema JSON.

Cách xử lý few-shot trong notebook này:
- `system_prompt.txt` giữ toàn bộ schema/quy tắc ổn định trong role `system`.
- `few_shots.txt` được đưa vào một message `user` ổn định ngay trước bài báo hiện tại. Cách này hợp với file few-shot đang là markdown/rút gọn, và giúp phần prefix lặp lại dễ được context cache.
- Bài báo hiện tại nằm ở message `user` cuối cùng, mỗi request chỉ xử lý một bài để tránh lẫn entity/event giữa các bài.
- API bật `response_format={"type": "json_object"}` để ép output là JSON hợp lệ theo hướng dẫn DeepSeek.

Nguồn API chính thức:
- Chat completions: https://api-docs.deepseek.com/api/create-chat-completion
- JSON output: https://api-docs.deepseek.com/guides/json_mode
- Models/pricing/cache fields: https://api-docs.deepseek.com/quick_start/pricing

In [1]:
from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path.cwd()
if not (ROOT / "data").exists():
    ROOT = ROOT.parent.parent

DATA_PATH = ROOT / "data/raw/cafef_raw/cafef_news_2023.csv"
SYSTEM_PROMPT_PATH = ROOT / "src/LLM_labeling/system_prompt.txt"
FEW_SHOTS_PATH = ROOT / "src/LLM_labeling/few_shots.txt"
OUTPUT_PATH = ROOT / "data/processed/cafef_2023_first1000.jsonl"

MODEL = "deepseek-v4-flash"
BASE_URL = "https://api.deepseek.com"
N_ROWS = 1000
REQUEST_SLEEP_SECONDS = 0.15
MAX_TOKENS = 8192
TEMPERATURE = 0
DISABLE_THINKING = True

print("ROOT:", ROOT)
print("DATA_PATH exists:", DATA_PATH.exists())
print("SYSTEM_PROMPT_PATH exists:", SYSTEM_PROMPT_PATH.exists())
print("FEW_SHOTS_PATH exists:", FEW_SHOTS_PATH.exists())

ROOT: /Users/buithianhdao/SE365
DATA_PATH exists: True
SYSTEM_PROMPT_PATH exists: True
FEW_SHOTS_PATH exists: True

In [2]:
system_prompt = SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
few_shots = FEW_SHOTS_PATH.read_text(encoding="utf-8").strip()

df = pd.read_csv(DATA_PATH).head(N_ROWS).copy()
df["article_id"] = df["article_id"].astype(str)

print("Rows:", len(df))
print("System prompt chars:", len(system_prompt))
print("Few-shot chars:", len(few_shots))
display(df[["article_id", "title", "summary", "published_date", "url"]].head(3))

Rows: 1000
System prompt chars: 15124
Few-shot chars: 8440

,article_id,title,summary,published_date,url
0,188231229103257892,"Thủy điện Hủa Na (HNA) ước lãi 217 tỷ đồng, lê...","Ngày 12/01/2024, hơn 235 triệu cổ phiếu HNA sẽ...",2023-12-29,https://cafef.vn/thuy-dien-hua-na-hna-uoc-lai-...
1,188231229094645055,Hành trình 16 năm và những dấu ấn tiên phong c...,Hành trình 16 năm từng bước chinh phục khách h...,2023-12-29,https://cafef.vn/hanh-trinh-16-nam-va-nhung-da...
2,188231229082554747,"UBCKNN xử phạt Công ty Đại Nam của ông Dũng ""L...",Công ty cổ phần Đại Nam bị phạt vì có hành vi ...,2023-12-29,https://cafef.vn/ubcknn-xu-phat-cong-ty-dai-na...

## Prompt Builders

`few_shots.txt` hiện là markdown ví dụ rút gọn, không phải các cặp `user`/`assistant` hoàn chỉnh. Vì vậy notebook dùng nó như một khối tham khảo ổn định. Nếu sau này bạn tạo few-shot đầy đủ dạng `input/output`, có thể đổi sang alternating messages: `user(example_input)`, `assistant(example_output)`, rồi mới tới bài thật.

In [3]:
def clean_text(value: Any) -> str:
    if pd.isna(value):
        return ""
    return str(value).strip()


def build_article_prompt(row: pd.Series) -> str:
    return f"""Bây giờ hãy trích xuất bài báo sau theo đúng schema JSON trong system prompt.

Yêu cầu bắt buộc:
- Chỉ trả về JSON hợp lệ, không markdown, không giải thích.
- `doc_id` nếu cần thì dùng article_id bên dưới.
- Nếu không có sự kiện tài chính rõ ràng: events = [] và main_topic = "other".

article_id: {clean_text(row.get('article_id'))}
source: {clean_text(row.get('source'))}
category: {clean_text(row.get('category'))}

TIÊU ĐỀ:
{clean_text(row.get('title'))}

TÓM TẮT:
{clean_text(row.get('summary'))}

NỘI DUNG:
{clean_text(row.get('content'))}
"""


def build_messages(row: pd.Series, include_few_shots: bool = True) -> list[dict[str, str]]:
    messages = [{"role": "system", "content": system_prompt}]
    if include_few_shots and few_shots:
        messages.append({
            "role": "user",
            "content": (
                "Dưới đây là các ví dụ mẫu. Hãy học cách chọn event_type, main_topic, "
                "cách điền attributes/context/evidence_text. Không trích xuất lại các ví dụ này.\n\n"
                f"{few_shots}"
            ),
        })
    messages.append({"role": "user", "content": build_article_prompt(row)})
    return messages


def extract_json_object(text: str) -> dict[str, Any]:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            return json.loads(text[start:end + 1])
        raise


preview_messages = build_messages(df.iloc[0])
print("Number of messages:", len(preview_messages))
for i, msg in enumerate(preview_messages):
    print(i, msg["role"], len(msg["content"]), msg["content"][:160].replace("\n", " "))

Number of messages: 3
0 system 15124 Bạn là hệ thống trích xuất sự kiện tài chính chuyên nghiệp cho thị trường chứng khoán Việt Nam. Nhiệm vụ của bạn là đọc MỘT bài báo tài chính tiếng Việt và tríc
1 user 8590 Dưới đây là các ví dụ mẫu. Hãy học cách chọn event_type, main_topic, cách điền attributes/context/evidence_text. Không trích xuất lại các ví dụ này.  ### Ví dụ
2 user 2564 Bây giờ hãy trích xuất bài báo sau theo đúng schema JSON trong system prompt.  Yêu cầu bắt buộc: - Chỉ trả về JSON hợp lệ, không markdown, không giải thích. - `

In [4]:
def deepseek_chat(messages: list[dict[str, str]], *, max_retries: int = 3) -> dict[str, Any]:
    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        raise RuntimeError("Missing DEEPSEEK_API_KEY. Set it before running API cells.")

    payload: dict[str, Any] = {
        "model": MODEL,
        "messages": messages,
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
        "response_format": {"type": "json_object"},
        "stream": False,
    }
    if DISABLE_THINKING:
        payload["thinking"] = {"type": "disabled"}

    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        f"{BASE_URL}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    for attempt in range(max_retries):
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            if e.code in {429, 500, 502, 503, 504} and attempt < max_retries - 1:
                time.sleep(2 ** attempt)
                continue
            raise RuntimeError(f"DeepSeek HTTP {e.code}: {error_body}") from e
        except urllib.error.URLError:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
                continue
            raise

    raise RuntimeError("DeepSeek request failed after retries")


def label_one(row: pd.Series, include_few_shots: bool = True) -> dict[str, Any]:
    messages = build_messages(row, include_few_shots=include_few_shots)
    response = deepseek_chat(messages)
    choice = response["choices"][0]
    content = choice["message"].get("content") or ""

    parsed: dict[str, Any] | None = None
    parse_error: str | None = None
    try:
        parsed = extract_json_object(content)
        parsed.setdefault("doc_id", clean_text(row.get("article_id")))
    except json.JSONDecodeError as e:
        # Keep raw_response/usage so malformed JSON can be inspected or repaired later.
        parse_error = repr(e)

    return {
        "article_id": clean_text(row.get("article_id")),
        "title": clean_text(row.get("title")),
        "published_date": clean_text(row.get("published_date")),
        "url": clean_text(row.get("url")),
        "label": parsed,
        "raw_response": content,
        "finish_reason": choice.get("finish_reason"),
        "usage": response.get("usage", {}),
        "model": response.get("model", MODEL),
        "response_id": response.get("id"),
        "error": parse_error,
    }

# Nhập DeepSeek API key

In [5]:
import os
import getpass

os.environ.pop("DEEPSEEK_API_KEY", None)
os.environ["DEEPSEEK_API_KEY"] = getpass.getpass("Nhập lại DeepSeek API key: ").strip()

## Test 1 Article

Chạy cell này trước để xem API key, JSON mode, prompt và schema có ổn không. Để tránh gọi API ngoài ý muốn, mặc định `RUN_ONE_API_CALL = False`.

In [6]:
RUN_ONE_API_CALL = False

if RUN_ONE_API_CALL:
    one_result = label_one(df.iloc[0], include_few_shots=True)
    print(json.dumps(one_result["label"], ensure_ascii=False, indent=2))
    print("usage:", one_result["usage"])
else:
    print("Dry run only. Set RUN_ONE_API_CALL = True to call DeepSeek for the first article.")
    print(build_article_prompt(df.iloc[0])[:1200])

Dry run only. Set RUN_ONE_API_CALL = True to call DeepSeek for the first article.
Bây giờ hãy trích xuất bài báo sau theo đúng schema JSON trong system prompt.

Yêu cầu bắt buộc:
- Chỉ trả về JSON hợp lệ, không markdown, không giải thích.
- `doc_id` nếu cần thì dùng article_id bên dưới.
- Nếu không có sự kiện tài chính rõ ràng: events = [] và main_topic = "other".

article_id: 188231229103257892
source: cafef
category: Thị trường chứng khoán

TIÊU ĐỀ:
Thủy điện Hủa Na (HNA) ước lãi 217 tỷ đồng, lên sàn HoSE ngay trong tháng 1/2024

TÓM TẮT:
Ngày 12/01/2024, hơn 235 triệu cổ phiếu HNA sẽ chính thức được giao dịch trên sàn HSX với giá tham chiếu trong ngày giao dịch đầu tiên là 18.350 đồng/cổ phiếu.

NỘI DUNG:
HNA:
Ngày 28/12/2023, Công ty Cổ phần Chứng khoán Rồng Việt (Rồng Việt) đã phối hợp cùng Công ty Cổ phần Thủy điện Hủa Na (Mã CK: HNA) tổ chức Hội nghị nhà đầu tư. Buổi hội thảo thu hút sự tham gia của các chuyên gia phân tích, nhân viên môi giới và đông đảo các Nhà đầu tư chứng khoán.
Tại hội thảo, Ban lãnh đạo Công ty Cổ phần Thủy điện Hủa Na đã giới thiệu tổng quan về Công ty cũng như kế ước tính kết quả kinh doanh năm 2023.
Theo đó, trong năm 2023, tổng sản lượng điện thương mại của Hủa Nam ước đạt 557.860mWh, doanh thu thuần ước tính 755 tỷ đồng và lợi

In [7]:
print(df.iloc[0]['content'] )

HNA:
Ngày 28/12/2023, Công ty Cổ phần Chứng khoán Rồng Việt (Rồng Việt) đã phối hợp cùng Công ty Cổ phần Thủy điện Hủa Na (Mã CK: HNA) tổ chức Hội nghị nhà đầu tư. Buổi hội thảo thu hút sự tham gia của các chuyên gia phân tích, nhân viên môi giới và đông đảo các Nhà đầu tư chứng khoán.
Tại hội thảo, Ban lãnh đạo Công ty Cổ phần Thủy điện Hủa Na đã giới thiệu tổng quan về Công ty cũng như kế ước tính kết quả kinh doanh năm 2023.
Theo đó, trong năm 2023, tổng sản lượng điện thương mại của Hủa Nam ước đạt 557.860mWh, doanh thu thuần ước tính 755 tỷ đồng và lợi nhuận sau thuế 217 tỷ đồng. Công ty hiện đang có kế hoạch tìm kiếm, nghiên cứu các dự án thủy điện quy mô vừa và nhỏ tại Nghệ An, Thanh Hóa, Tây Nguyên. Ngoài ra, Hủa Na cũng nghiên cứu thực hiện dự án điện mặt trời ở lòng hồ thủy điện Hủa Na.
Hiện tại, Hủa Na đang vận hành nhà máy điện Hủa Na với giá bán điện bình quân 1.186 đồng/kWh.
Tại hội thảo, đại diện Thủy điện Hủa Na cũng chia sẻ với các nhà đầu tư về việc niêm yết cổ phiếu HNA của Công ty tại Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh (HSX). Theo đó, ngày 12/01/2024, hơn 235 triệu cổ phiếu HNA sẽ chính thức được giao dịch trên sàn HSX với giá tham chiếu trong ngày giao dịch đầu tiên là 18.350 đồng/cổ phiếu. Theo Ban lãnh đạo Công ty Cổ phần Thủy điện Hủa Na, việc niêm yết cổ phiếu trên HSX có nhiều ý nghĩa trong chiến lược phát triển của Công ty, giúp khẳng định sự hấp dẫn đối với các nhà đầu tư và phát huy hơn nữa hình ảnh của Công ty Cổ phần Thủy điện Hủa Na.
Trong khuôn khổ buổi hội thảo, Công ty Cổ phần Thủy điện Hủa Na cũng đã có phần hỏi đáp cùng Nhà đầu tư tham dự buổi Hội thảo. Câu hỏi được Nhà đầu tư quan tâm nhiều nhất là tình hình hoạt động hiện tại của Nhà máy Thủy điện Hủa Na và kế hoạch phát triển trong tương lai. Với năng lực và dự án hiện có, Công ty Cổ phần Thủy điện Hủa Na cho biết rất tin tưởng về khả năng hoàn thành kế hoạch sản xuất kinh doanh trong dài hạn.

## Batch Label First 1000 Rows

Output được append vào JSONL. Nếu notebook dừng giữa chừng, chạy lại cell này sẽ bỏ qua `article_id` đã có trong output.

In [8]:
RUN_BATCH = True

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

processed_ids: set[str] = set()
# Chỉ skip các article_id đã label thành công. Các dòng lỗi sẽ được retry.
if OUTPUT_PATH.exists():
    with OUTPUT_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                record = json.loads(line)
                if record.get("label") is not None and not record.get("error"):
                    processed_ids.add(str(record.get("article_id")))

todo = df.loc[~df["article_id"].isin(processed_ids)].copy()
print("Output:", OUTPUT_PATH)
print("Already processed:", len(processed_ids))
print("Todo:", len(todo))

if RUN_BATCH:
    with OUTPUT_PATH.open("a", encoding="utf-8") as out:
        for n, (_, row) in enumerate(todo.iterrows(), start=1):
            article_id = clean_text(row.get("article_id"))
            try:
                result = label_one(row, include_few_shots=True)
                result.setdefault("error", None)
            except Exception as e:
                result = {
                    "article_id": article_id,
                    "title": clean_text(row.get("title")),
                    "published_date": clean_text(row.get("published_date")),
                    "url": clean_text(row.get("url")),
                    "label": None,
                    "raw_response": None,
                    "finish_reason": None,
                    "usage": {},
                    "model": MODEL,
                    "error": repr(e),
                }
            out.write(json.dumps(result, ensure_ascii=False) + "\n")
            out.flush()
            if n % 10 == 0 or result.get("error"):
                print(f"{n}/{len(todo)} article_id={article_id} error={result.get('error')}")
            time.sleep(REQUEST_SLEEP_SECONDS)
else:
    print("Dry run only. Set RUN_BATCH = True to label the first 1000 rows.")

Output: /Users/buithianhdao/SE365/data/processed/cafef_2023_first1000.jsonl
Already processed: 0
Todo: 1000
10/1000 article_id=188231228133628241 error=None
20/1000 article_id=188231227185121636 error=None
30/1000 article_id=188231227103309926 error=None
40/1000 article_id=188231225160441405 error=None
50/1000 article_id=18823122509020593 error=None
60/1000 article_id=188231224121555926 error=None
70/1000 article_id=188231221002530769 error=None
80/1000 article_id=188231222133550946 error=None
90/1000 article_id=188231221191212787 error=None
100/1000 article_id=18823121909024836 error=None
110/1000 article_id=188231220150404752 error=None
120/1000 article_id=18823121710424306 error=None
130/1000 article_id=188231216231645356 error=None
140/1000 article_id=188231218141828788 error=None
150/1000 article_id=188231214183448573 error=None
160/1000 article_id=188231214075029919 error=None
170/1000 article_id=1882312150942061 error=None
180/1000 article_id=188231212215557139 error=None
190/1000 article_id=188231212143031963 error=None
200/1000 article_id=188231211185031323 error=None
210/1000 article_id=188231211152351651 error=None
220/1000 article_id=188231210234342465 error=None
230/1000 article_id=188231206231137471 error=None
240/1000 article_id=188231208105608745 error=None
250/1000 article_id=18823120716473518 error=None
260/1000 article_id=188231205125208176 error=None
270/1000 article_id=188231204174637432 error=None
280/1000 article_id=188231203231636652 error=None
290/1000 article_id=188231129192023027 error=None
300/1000 article_id=188231129105902828 error=None
310/1000 article_id=188231128165117901 error=None
320/1000 article_id=188231127233258307 error=None
330/1000 article_id=188231127093344328 error=None
340/1000 article_id=188231125153420738 error=None
350/1000 article_id=188231124165317626 error=None
360/1000 article_id=188231122001512754 error=None
370/1000 article_id=188231120232812746 error=None
380/1000 article_id=188231120094516092 error=None
390/1000 article_id=188231119100821352 error=None
400/1000 article_id=188230817155427096 error=None
410/1000 article_id=188231116150019225 error=None
420/1000 article_id=188231115183951674 error=None
430/1000 article_id=188231113143705047 error=None
440/1000 article_id=18823111213365253 error=None
450/1000 article_id=188231111155144152 error=None
460/1000 article_id=188231110133200227 error=None
470/1000 article_id=188231109092517458 error=None
480/1000 article_id=18823110820265828 error=None
490/1000 article_id=188231108113624714 error=None
500/1000 article_id=188231106121600745 error=None
510/1000 article_id=188231106081344549 error=None
520/1000 article_id=188231104230547332 error=None
530/1000 article_id=188231101224108617 error=None
540/1000 article_id=188231101140948468 error=None
550/1000 article_id=188231102153903895 error=None
560/1000 article_id=188231031173130988 error=None
570/1000 article_id=188231031105209068 error=None
580/1000 article_id=188231030201930529 error=None
590/1000 article_id=188231030131212039 error=None
600/1000 article_id=188231029225600326 error=None
610/1000 article_id=188231027172413737 error=None
620/1000 article_id=188231027114123816 error=None
630/1000 article_id=188231026185910769 error=None
640/1000 article_id=188231026145132341 error=None
650/1000 article_id=188231024152947702 error=None
660/1000 article_id=188231024085431435 error=None
670/1000 article_id=188231025151129379 error=None
680/1000 article_id=188231022230407404 error=None
690/1000 article_id=188231021231646111 error=None
700/1000 article_id=188231023110922723 error=None
710/1000 article_id=188231019152354923 error=None
720/1000 article_id=188231018203825368 error=None
730/1000 article_id=188231019224703338 error=None
740/1000 article_id=188231017231346075 error=None
750/1000 article_id=188231018190228862 error=None
751/1000 article_id=188231018162948666 error=JSONDecodeError("Expecting ',' delimiter: line 563 column 8 (char 22822)")
760/1000 article_id=18823101811373627 error=None
770/1000 article_id=18823101710363257 error=None
777/1000 article_id=188231016232723004 error=JSONDecodeError("Expecting ',' delimiter: line 497 column 8 (char 22399)")
780/1000 article_id=188231016212558162 error=None
790/1000 article_id=188231016133433397 error=None
800/1000 article_id=188231015224902135 error=None
810/1000 article_id=188231014082740433 error=None
820/1000 article_id=188231013121612701 error=None
826/1000 article_id=188231012223618351 error=JSONDecodeError("Expecting ',' delimiter: line 513 column 6 (char 22872)")
830/1000 article_id=18823101219435222 error=None
840/1000 article_id=188231010145302294 error=None
850/1000 article_id=188231009221413201 error=None
860/1000 article_id=188231009140754498 error=None
870/1000 article_id=188231008185736019 error=None
880/1000 article_id=188231007134603073 error=None
890/1000 article_id=188231005110628309 error=None
893/1000 article_id=188231004232035666 error=JSONDecodeError("Expecting ',' delimiter: line 537 column 6 (char 22561)")
900/1000 article_id=188231006170951258 error=None
910/1000 article_id=188231006071640288 error=None
920/1000 article_id=188231004154204104 error=None
930/1000 article_id=188231002182301483 error=None
940/1000 article_id=188231002075631668 error=None
950/1000 article_id=188230930220559336 error=None
960/1000 article_id=188230929172910186 error=None
970/1000 article_id=188230928230844505 error=None
980/1000 article_id=188230928105308335 error=None
985/1000 article_id=188230927230433619 error=JSONDecodeError("Expecting ',' delimiter: line 498 column 8 (char 22145)")
990/1000 article_id=188230927192551999 error=None
1000/1000 article_id=188230927152617991 error=None

## Inspect Results And Cost Tokens

In [9]:
def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


records = load_jsonl(OUTPUT_PATH)
print("records:", len(records))
if records:
    result_df = pd.DataFrame(records)
    result_df["raw_response_chars"] = result_df["raw_response"].apply(lambda x: len(x) if isinstance(x, str) else 0)
    display(result_df[["article_id", "title", "published_date", "error", "finish_reason", "raw_response_chars"]].head(20))

    usage = pd.json_normalize([r.get("usage", {}) for r in records])
    if not usage.empty:
        print(usage.sum(numeric_only=True).to_string())

    labels = [r.get("label") for r in records if r.get("label")]
    event_counts = {}
    for label in labels:
        for event in label.get("events", []) or []:
            event_type = event.get("event_type")
            event_counts[event_type] = event_counts.get(event_type, 0) + 1
    print("event_counts:")
    print(json.dumps(dict(sorted(event_counts.items(), key=lambda x: str(x[0]))), ensure_ascii=False, indent=2))

records: 1000

,article_id,title,published_date,error,finish_reason,raw_response_chars
0,188231229103257892,"Thủy điện Hủa Na (HNA) ước lãi 217 tỷ đồng, lê...",2023-12-29,None,stop,2695
1,188231229094645055,Hành trình 16 năm và những dấu ấn tiên phong c...,2023-12-29,None,stop,750
2,188231229082554747,"UBCKNN xử phạt Công ty Đại Nam của ông Dũng ""L...",2023-12-29,None,stop,1797
3,188231228162951823,Từng gây chấn động với giá gần 1 triệu đồng/cp...,2023-12-29,None,stop,3582
4,188231228183151294,Góc nhìn CTCK: Rung lắc có thể sớm xuất hiện k...,2023-12-28,None,stop,1831
5,18823122817101572,"Cùng chiều khối ngoại, tự doanh CTCK mua ròng ...",2023-12-28,None,stop,3122
6,188231228165707197,Cổ phiếu nhà Vingroup tiếp tục gây chú ý,2023-12-28,None,stop,5124
7,188231228164957233,Hãng dược hơn trăm tuổi Nhật Bản tung 200 tỷ m...,2023-12-28,None,stop,3003
8,18823122815555081,Khối ngoại tiếp đà mua ròng 330 tỷ đồng trong ...,2023-12-28,None,stop,16297
9,188231228133628241,Cổ phiếu của một công ty vốn nghìn tỷ bị huỷ n...,2023-12-28,None,stop,1762
10,188231228125753636,Chứng khoán 2023: Bước đệm cho hành trình nâng...,2023-12-28,None,stop,12660
11,188231228113546171,"Dự báo VN-Index lên 1.460 điểm trong năm 2024,...",2023-12-28,None,stop,2423
12,188231228105806736,"""Đến hẹn lại lên"", Đạm Cà Mau (DCM) năm thứ ba...",2023-12-28,None,stop,3446
13,188231227165513427,Bật mí “chiến lược” VPBankS: Trở thành One-Sto...,2023-12-28,None,stop,731
14,188231227163609233,Lịch sự kiện và tin vắn chứng khoán ngày 28/12,2023-12-28,None,stop,16958
15,188231227172408388,Một nhóm ngành được dự báo tăng trưởng lợi nhu...,2023-12-28,None,stop,1196
16,188231227210317595,"Trái phiếu doanh nghiệp, bảo hiểm... ế",2023-12-27,None,stop,4848
17,188231227210010218,Cổ phiếu Vinhomes xuất hiện giao dịch lớn nhất...,2023-12-27,None,stop,2780
18,188231227191807944,Góc nhìn CTCK: VN-Index có thể sớm gặp áp lực ...,2023-12-27,None,stop,1709
19,188231227185121636,Phiên 27/12: Tự doanh CTCK mua ròng 400 tỷ trê...,2023-12-27,None,stop,4929

prompt_tokens                          10531217
completion_tokens                       1426644
total_tokens                           11957861
prompt_cache_hit_tokens                 9181184
prompt_cache_miss_tokens                1350033
prompt_tokens_details.cached_tokens     9181184
event_counts:
{
  "declare_bankruptcy": 6,
  "dividend": 270,
  "earnings_report": 399,
  "equity_freeze": 7,
  "equity_overweight": 236,
  "equity_repurchase": 9,
  "equity_underweight": 311,
  "lawsuit": 20,
  "legal_penalty": 110,
  "macro_indicator": 145,
  "merge_org": 12,
  "other": 36,
  "personnel_change": 76,
  "price_movement": 999,
  "share_issuance": 209,
  "transfer_money": 47,
  "transfer_ownership": 60
}

## Inspect Raw Response For Failed Articles

Sau khi batch chạy, dùng helper này để in `raw_response` của một `article_id`, nhất là các dòng bị `JSONDecodeError`.

In [11]:
import re


def show_raw_response(article_id: str, *, full: bool = False, context_chars: int = 1200) -> None:
    records = load_jsonl(OUTPUT_PATH)
    matches = [r for r in records if str(r.get("article_id")) == str(article_id)]
    print("matches:", len(matches))
    if not matches:
        return

    for idx, record in enumerate(matches, start=1):
        raw = record.get("raw_response")
        error = record.get("error")
        print("\n--- match", idx, "---")
        print("title:", record.get("title"))
        print("error:", error)
        print("finish_reason:", record.get("finish_reason"))
        print("usage:", record.get("usage"))
        print("raw_response_chars:", len(raw) if isinstance(raw, str) else None)

        if not isinstance(raw, str):
            print("raw_response is None. Record này có thể được tạo trước khi sửa notebook; hãy chạy lại batch cho article này.")
            continue

        if full:
            print(raw)
            continue

        match = re.search(r"char (\d+)", str(error))
        if match:
            pos = int(match.group(1))
            start = max(0, pos - context_chars)
            end = min(len(raw), pos + context_chars)
            print(f"showing raw_response[{start}:{end}] around char {pos}:")
            print(raw[start:end])
        else:
            print(f"showing raw_response[:{context_chars}]:")
            print(raw[:context_chars])


# Example:
show_raw_response("188231220091258805")
show_raw_response("188231220091258805", full=True)

matches: 1

--- match 1 ---
title: Lịch sự kiện và tin vắn chứng khoán ngày 20/12
error: None
finish_reason: stop
usage: {'prompt_tokens': 10496, 'completion_tokens': 4903, 'total_tokens': 15399, 'prompt_tokens_details': {'cached_tokens': 10368}, 'prompt_cache_hit_tokens': 10368, 'prompt_cache_miss_tokens': 128}
raw_response_chars: 13559
showing raw_response[:1200]:
{
  "doc_id": "188231220091258805",
  "language": "vi",
  "main_topic": "ownership_change",
  "entities": [
    {"name": "PYN ELITE FUND (NON-UCITS)", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn", "type": "Company", "ticker": "SCS", "role_in_article": "mentioned"},
    {"name": "CT TNHH Sài Gòn 3 Jean", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Pin Ắc quy miền Nam", "type": "Company", "ticker": "PAC", "role_in_article": "mentioned"},
    {"name": "Nguyễn Thị Nga", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP SAMETEL", "type": "Company", "ticker": "SMT", "role_in_article": "mentioned"},
    {"name": "Trương Huy Tâm", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP Tập đoàn VEXILLA Việt Nam", "type": "Company", "ticker": "SVN", "role_in_article": "mentioned"},
    {"name": "Võ Thiên Chương", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Trang", "type": "Company", "ticker": "TFC", "role_in_article": "mentioned"},
    {"name"
matches: 1

--- match 1 ---
title: Lịch sự kiện và tin vắn chứng khoán ngày 20/12
error: None
finish_reason: stop
usage: {'prompt_tokens': 10496, 'completion_tokens': 4903, 'total_tokens': 15399, 'prompt_tokens_details': {'cached_tokens': 10368}, 'prompt_cache_hit_tokens': 10368, 'prompt_cache_miss_tokens': 128}
raw_response_chars: 13559
{
  "doc_id": "188231220091258805",
  "language": "vi",
  "main_topic": "ownership_change",
  "entities": [
    {"name": "PYN ELITE FUND (NON-UCITS)", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn", "type": "Company", "ticker": "SCS", "role_in_article": "mentioned"},
    {"name": "CT TNHH Sài Gòn 3 Jean", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Pin Ắc quy miền Nam", "type": "Company", "ticker": "PAC", "role_in_article": "mentioned"},
    {"name": "Nguyễn Thị Nga", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP SAMETEL", "type": "Company", "ticker": "SMT", "role_in_article": "mentioned"},
    {"name": "Trương Huy Tâm", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP Tập đoàn VEXILLA Việt Nam", "type": "Company", "ticker": "SVN", "role_in_article": "mentioned"},
    {"name": "Võ Thiên Chương", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Trang", "type": "Company", "ticker": "TFC", "role_in_article": "mentioned"},
    {"name": "Lê Thị Hồng Hạnh", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP Bảo hiểm Ngân hàng Nông Nghiệp", "type": "Company", "ticker": "ABI", "role_in_article": "mentioned"},
    {"name": "Vũ Thúy Hạnh", "type": "Person", "ticker": null, "role_in_article": "subject"}
  ],
  "events": [
    {
      "event_type": "equity_underweight",
      "entities_involved": ["PYN ELITE FUND (NON-UCITS)", "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn"],
      "context": {
        "who": "PYN ELITE FUND (NON-UCITS)",
        "what": "Bán 200.000 cổ phiếu SCS",
        "when": "14/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là gần 5,5 triệu cổ phiếu (5,8% vốn)"
      },
      "attributes": {
        "equity_holder": "PYN ELITE FUND (NON-UCITS)",
        "traded_shares": 200000,
        "start_date": "2023-12-14",
        "end_date": "2023-12-14",
        "average_price": null,
        "later_holding_shares": 5500000
      },
      "evidence_text": "PYN ELITE FUND (NON-UCITS) đã bán 200.000 cổ phiếu SCS. Số lượng cổ phiếu nắm giữ sau khi thực hiện giao dịch là gần 5,5 triệu cổ phiếu tương ứng 5,8% vốn.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["CT TNHH Sài Gòn 3 Jean", "Công ty Cổ phần Pin Ắc quy miền Nam"],
      "context": {
        "who": "CT TNHH Sài Gòn 3 Jean",
        "what": "Mua 3 triệu cổ phiếu PAC",
        "when": "14/12/2023 - 15/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là 3 triệu cổ phiếu (6,46% vốn)"
      },
      "attributes": {
        "equity_holder": "CT TNHH Sài Gòn 3 Jean",
        "trading_shares": 3000000,
        "date": "14/12/2023 - 15/12/2023",
        "later_holding_shares": 3000000,
        "later_holding_pct": 6.46,
        "average_price": null
      },
      "evidence_text": "CT TNHH Sài Gòn 3 Jean đã mua 3 triệu cổ phiếu PAC, tăng sở hữu lên 3 triệu cổ phiếu, tỷ lệ 6,46%.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Nguyễn Thị Nga", "CTCP SAMETEL"],
      "context": {
        "who": "Nguyễn Thị Nga",
        "what": "Mua 139.200 cổ phiếu SMT",
        "when": "13/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là 528.200 cổ phiếu (9,66% vốn)"
      },
      "attributes": {
        "equity_holder": "Nguyễn Thị Nga",
        "trading_shares": 139200,
        "date": "13/12/2023",
        "later_holding_shares": 528200,
        "later_holding_pct": 9.66,
        "average_price": null
      },
      "evidence_text": "Cổ đông lớn Nguyễn Thị Nga đã mua 139.200 cổ phiếu SMT. Số lượng cổ phiếu nắm giữ sau khi thực hiện giao dịch là 528.200 cổ phiếu (tỷ lệ 9,66%).",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Trương Huy Tâm", "CTCP Tập đoàn VEXILLA Việt Nam"],
      "context": {
        "who": "Trương Huy Tâm",
        "what": "Mua 649.900 cổ phiếu SVN",
        "when": "7/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là 1.269.900 cổ phiếu (6,05% vốn)"
      },
      "attributes": {
        "equity_holder": "Trương Huy Tâm",
        "trading_shares": 649900,
        "date": "7/12/2023",
        "later_holding_shares": 1269900,
        "later_holding_pct": 6.05,
        "average_price": null
      },
      "evidence_text": "Cổ đông lớn Trương Huy Tâm đã mua 649.900 cổ phiếu SVN. Số lượng cổ phiếu nắm giữ sau khi thực hiện giao dịch là 1.269.900 cổ phiếu (tỷ lệ 6,05%).",
      "confidence": 0.95
    },
    {
      "event_type": "equity_underweight",
      "entities_involved": ["Võ Thiên Chương", "Công ty Cổ phần Trang"],
      "context": {
        "who": "Võ Thiên Chương",
        "what": "Đăng ký bán 200.000 cổ phiếu TFC",
        "when": "21/12/2023 - 18/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "equity_holder": "Võ Thiên Chương",
        "traded_shares": 200000,
        "start_date": "2023-12-21",
        "end_date": "2024-01-18",
        "average_price": null,
        "later_holding_shares": null
      },
      "evidence_text": "Ủy viên HĐQT Võ Thiên Chương đăng ký bán 200.000 cổ phiếu TFC. Thời gian giao dịch dự kiến từ 21/12/2023 đến 18/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Lê Thị Hồng Hạnh", "CTCP Bảo hiểm Ngân hàng Nông Nghiệp"],
      "context": {
        "who": "Lê Thị Hồng Hạnh",
        "what": "Đăng ký mua 120.000 cổ phiếu ABI",
        "when": "22/12/2023 - 19/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "equity_holder": "Lê Thị Hồng Hạnh",
        "trading_shares": 120000,
        "date": "22/12/2023 - 19/1/2024",
        "later_holding_shares": null,
        "later_holding_pct": null,
        "average_price": null
      },
      "evidence_text": "Bà Lê Thị Hồng Hạnh đăng ký mua 120.000 cổ phiếu ABI. Thời gian giao dịch dự kiến từ 22/12/2023 đến 19/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Vũ Thúy Hạnh", "CTCP Bảo hiểm Ngân hàng Nông Nghiệp"],
      "context": {
        "who": "Vũ Thúy Hạnh",
        "what": "Đăng ký mua 200.000 cổ phiếu ABI",
        "when": "21/12/2023 - 29/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "equity_holder": "Vũ Thúy Hạnh",
        "trading_shares": 200000,
        "date": "21/12/2023 - 29/12/2023",
        "later_holding_shares": null,
        "later_holding_pct": null,
        "average_price": null
      },
      "evidence_text": "Bà Vũ Thúy Hạnh đăng ký mua 200.000 cổ phiếu ABI. Thời gian giao dịch dự kiến từ 21/12/2023 đến 29/12/2023.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh"],
      "context": {
        "who": "Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh",
        "what": "Tạm ứng cổ tức năm 2023 bằng tiền mặt tổng tỷ lệ 30%",
        "when": "Ngày đăng ký cuối cùng 29/12/2023, chi trả đợt 1 ngày 31/1/2024, đợt 2 ngày 22/3/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 30,
        "dividend_per_share": {"value": 3000, "unit": "VND/share"},
        "ex_date": "2023-12-29",
        "payment_date": "2024-01-31",
        "total_amount": null
      },
      "evidence_text": "Ngày 29/12 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận tạm ứng cổ tức năm 2023 bằng tiền mặt tổng tỷ lệ 30% (tương ứng mỗi cổ phiếu nhận về 3.000 đồng). VSH dự kiến chi trả đợt 1 (10%) vào 31/1/2024 và đợt 2 (20%) vào 22/3/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["Công ty Cổ phần Nhiên liệu Sài Gòn"],
      "context": {
        "who": "Công ty Cổ phần Nhiên liệu Sài Gòn",
        "what": "Chi trả cổ tức năm 2023 bằng tiền mặt tỷ lệ 20%",
        "when": "Ngày đăng ký cuối cùng 19/1/2024, chi trả ngày 24/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 20,
        "dividend_per_share": {"value": 2000, "unit": "VND/share"},
        "ex_date": "2024-01-19",
        "payment_date": "2024-01-24",
        "total_amount": null
      },
      "evidence_text": "Ngày 19/1/2024 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận cổ tức năm 2023 bằng tiền mặt tỷ lệ 20% (tương ứng mỗi cổ phiếu nhận về 2.000 đồng). SFC dự kiến chi trả vào 24/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["CTCP Que hàn điện Việt Đức"],
      "context": {
        "who": "CTCP Que hàn điện Việt Đức",
        "what": "Chi trả cổ tức năm 2023 bằng tiền mặt tỷ lệ 20%",
        "when": "Ngày đăng ký cuối cùng 29/12/2023, chi trả ngày 22/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 20,
        "dividend_per_share": {"value": 2000, "unit": "VND/share"},
        "ex_date": "2023-12-29",
        "payment_date": "2024-01-22",
        "total_amount": null
      },
      "evidence_text": "Ngày 29/12 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận cổ tức năm 2023 bằng tiền mặt tỷ lệ 20% (tương ứng mỗi cổ phiếu nhận về 2.000 đồng). QHD dự kiến chi trả vào 22/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["CTCP Vật liệu Xây dựng và Trang trí Nội thất Thành phố Hồ Chí Minh"],
      "context": {
        "who": "CTCP Vật liệu Xây dựng và Trang trí Nội thất Thành phố Hồ Chí Minh",
        "what": "Chi trả cổ tức năm 2023 bằng tiền mặt tỷ lệ 20%",
        "when": "Ngày đăng ký cuối cùng 12/1/2024, chi trả ngày 25/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 20,
        "dividend_per_share": {"value": 2000, "unit": "VND/share"},
        "ex_date": "2024-01-12",
        "payment_date": "2024-01-25",
        "total_amount": null
      },
      "evidence_text": "Ngày 12/1/2024 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận cổ tức năm 2023 bằng tiền mặt tỷ lệ 20% (tương ứng mỗi cổ phiếu nhận về 2.000 đồng). CMD dự kiến chi trả vào 25/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "transfer_ownership",
      "entities_involved": ["Công ty Cổ phần Xuất Nhập Khẩu An Giang", "CTCP The Golden Group"],
      "context": {
        "who": "Công ty Cổ phần Xuất Nhập Khẩu An Giang",
        "what": "Chuyển nhượng 21% vốn góp tại AGM Furious cho CTCP The Golden Group",
        "when": null,
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "transferor": "Công ty Cổ phần Xuất Nhập Khẩu An Giang",
        "transferee": "CTCP The Golden Group",
        "asset_description": "21% vốn góp tại AGM Furious",
        "value": null,
        "stake_pct": 21
      },
      "evidence_text": "Thông báo Nghị quyết HĐQT về việc chuyển nhượng 21% vốn góp tại AGM Furious cho CTCP The Golden Group.",
      "confidence": 0.9
    },
    {
      "event_type": "earnings_report",
      "entities_involved": ["Công ty Cổ phần Phân bón Dầu khí Cà Mau"],
      "context": {
        "who": "Công ty Cổ phần Phân bón Dầu khí Cà Mau",
        "what": "Công bố kế hoạch SXKD năm 2024",
        "when": "năm 2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "period": "năm 2024",
        "revenue": {"value": 11878, "unit": "tỷ VND", "yoy_change_pct": null},
        "net_profit": {"value": 795, "unit": "tỷ VND", "yoy_change_pct": null},
        "eps": null,
        "vs_forecast": null
      },
      "evidence_text": "Thông báo các chỉ tiêu kế hoạch hoạt động SXKD chính năm 2024, trong đó kế hoạch tổng doanh thu hợp nhất 11.878 tỷ và LNST 795 tỷ đồng.",
      "confidence": 0.95
    }
  ],
  "summary": "Tổng hợp tin vắn chứng khoán ngày 20/12: giao dịch cổ đông lớn tại SCS, PAC, SMT, SVN; đăng ký giao dịch tại TFC, ABI; cổ tức tiền mặt tại VSH, SFC, QHD, CMD; chuyển nhượng vốn tại AGM; kế hoạch kinh doanh 2024 của DCM."
}