# Label CafeF 2023 With DeepSeek V4 Flash

Notebook này đọc 1.000 dòng đầu từ `data/raw/cafef_raw/cafef_news_2023.csv`, nạp `system_prompt.txt` và `few_shots.txt`, rồi gọi DeepSeek Chat Completions để trích xuất sự kiện tài chính theo schema JSON.

Cách xử lý few-shot trong notebook này:
- `system_prompt.txt` giữ toàn bộ schema/quy tắc ổn định trong role `system`.
- `few_shots.txt` được đưa vào một message `user` ổn định ngay trước bài báo hiện tại. Cách này hợp với file few-shot đang là markdown/rút gọn, và giúp phần prefix lặp lại dễ được context cache.
- Bài báo hiện tại nằm ở message `user` cuối cùng, mỗi request chỉ xử lý một bài để tránh lẫn entity/event giữa các bài.
- API bật `response_format={"type": "json_object"}` để ép output là JSON hợp lệ theo hướng dẫn DeepSeek.

Nguồn API chính thức:
- Chat completions: https://api-docs.deepseek.com/api/create-chat-completion
- JSON output: https://api-docs.deepseek.com/guides/json_mode
- Models/pricing/cache fields: https://api-docs.deepseek.com/quick_start/pricing

In [13]:
from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path.cwd()
if not (ROOT / "data").exists():
    ROOT = ROOT.parent.parent

DATA_PATH = ROOT / "data/raw_news/merged_news.csv"
SYSTEM_PROMPT_PATH = ROOT / "src/LLM_labeling/system_prompt.txt"
FEW_SHOTS_PATH = ROOT / "src/LLM_labeling/few_shots.txt"
OUTPUT_PATH = ROOT / "data/processed/10k_labeled_news.jsonl"

MODEL = "deepseek-v4-flash"
BASE_URL = "https://api.deepseek.com"
N_ROWS = 20000
REQUEST_SLEEP_SECONDS = 0.15
MAX_TOKENS = 8192
TEMPERATURE = 0
DISABLE_THINKING = True

print("ROOT:", ROOT)
print("DATA_PATH exists:", DATA_PATH.exists())
print("SYSTEM_PROMPT_PATH exists:", SYSTEM_PROMPT_PATH.exists())
print("FEW_SHOTS_PATH exists:", FEW_SHOTS_PATH.exists())

ROOT: /Users/buithianhdao/SE365
DATA_PATH exists: True
SYSTEM_PROMPT_PATH exists: True
FEW_SHOTS_PATH exists: True

In [14]:
system_prompt = SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
few_shots = FEW_SHOTS_PATH.read_text(encoding="utf-8").strip()

#Randomly sample N_ROWS from the dataset to avoid hitting the API limit
df = pd.read_csv(DATA_PATH).sample(n=N_ROWS, random_state=42).copy()

df["article_id"] = df["article_id"].astype(str)

print("Rows:", len(df))
print("System prompt chars:", len(system_prompt))
print("Few-shot chars:", len(few_shots))
display(df[["article_id", "title", "summary", "published_date", "url"]].head(3))

Rows: 20000
System prompt chars: 15124
Few-shot chars: 8440

,article_id,title,summary,published_date,url
22065,188251007222809692,UBCKNN phát cảnh báo nóng đến những nhà đầu tư...,"UBCKNN khuyến cáo nhà đầu tư thận trọng, đồng ...",2025-10-08,https://cafef.vn/ubcknn-phat-canh-bao-nong-den...
20318,188251225225755762,Lịch sự kiện và tin vắn chứng khoán ngày 26/12...,Tổng hợp toàn bộ tin vắn nổi bật liên quan đến...,2025-12-26,https://cafef.vn/lich-su-kien-va-tin-van-chung...
9527,1184617,Theo dấu dòng tiền cá mập 26/04: Khối ngoại mu...,"Phiên ngày 26/04, khối tự doanh công ty chứng ...",2024-04-26,https://vietstock.vn/2024/04/theo-dau-dong-tie...

## Prompt Builders

`few_shots.txt` hiện là markdown ví dụ rút gọn, không phải các cặp `user`/`assistant` hoàn chỉnh. Vì vậy notebook dùng nó như một khối tham khảo ổn định. Nếu sau này bạn tạo few-shot đầy đủ dạng `input/output`, có thể đổi sang alternating messages: `user(example_input)`, `assistant(example_output)`, rồi mới tới bài thật.

In [3]:
def clean_text(value: Any) -> str:
    if pd.isna(value):
        return ""
    return str(value).strip()


def build_article_prompt(row: pd.Series) -> str:
    return f"""Bây giờ hãy trích xuất bài báo sau theo đúng schema JSON trong system prompt.

Yêu cầu bắt buộc:
- Chỉ trả về JSON hợp lệ, không markdown, không giải thích.
- `doc_id` nếu cần thì dùng article_id bên dưới.
- Nếu không có sự kiện tài chính rõ ràng: events = [] và main_topic = "other".

article_id: {clean_text(row.get('article_id'))}
source: {clean_text(row.get('source'))}
category: {clean_text(row.get('category'))}

TIÊU ĐỀ:
{clean_text(row.get('title'))}

TÓM TẮT:
{clean_text(row.get('summary'))}

NỘI DUNG:
{clean_text(row.get('content'))}
"""


def build_messages(row: pd.Series, include_few_shots: bool = True) -> list[dict[str, str]]:
    messages = [{"role": "system", "content": system_prompt}]
    if include_few_shots and few_shots:
        messages.append({
            "role": "user",
            "content": (
                "Dưới đây là các ví dụ mẫu. Hãy học cách chọn event_type, main_topic, "
                "cách điền attributes/context/evidence_text. Không trích xuất lại các ví dụ này.\n\n"
                f"{few_shots}"
            ),
        })
    messages.append({"role": "user", "content": build_article_prompt(row)})
    return messages


def extract_json_object(text: str) -> dict[str, Any]:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            return json.loads(text[start:end + 1])
        raise


preview_messages = build_messages(df.iloc[0])
print("Number of messages:", len(preview_messages))
for i, msg in enumerate(preview_messages):
    print(i, msg["role"], len(msg["content"]), msg["content"][:160].replace("\n", " "))

Number of messages: 3
0 system 15124 Bạn là hệ thống trích xuất sự kiện tài chính chuyên nghiệp cho thị trường chứng khoán Việt Nam. Nhiệm vụ của bạn là đọc MỘT bài báo tài chính tiếng Việt và tríc
1 user 8590 Dưới đây là các ví dụ mẫu. Hãy học cách chọn event_type, main_topic, cách điền attributes/context/evidence_text. Không trích xuất lại các ví dụ này.  ### Ví dụ
2 user 1618 Bây giờ hãy trích xuất bài báo sau theo đúng schema JSON trong system prompt.  Yêu cầu bắt buộc: - Chỉ trả về JSON hợp lệ, không markdown, không giải thích. - `

In [9]:
def deepseek_chat(messages: list[dict[str, str]], *, max_retries: int = 3) -> dict[str, Any]:
    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        raise RuntimeError("Missing DEEPSEEK_API_KEY. Set it before running API cells.")

    payload: dict[str, Any] = {
        "model": MODEL,
        "messages": messages,
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
        "response_format": {"type": "json_object"},
        "stream": False,
    }
    if DISABLE_THINKING:
        payload["thinking"] = {"type": "disabled"}

    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        f"{BASE_URL}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    for attempt in range(max_retries):
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            if e.code in {429, 500, 502, 503, 504} and attempt < max_retries - 1:
                time.sleep(2 ** attempt)
                continue
            raise RuntimeError(f"DeepSeek HTTP {e.code}: {error_body}") from e
        except urllib.error.URLError:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
                continue
            raise

    raise RuntimeError("DeepSeek request failed after retries")


def label_one(row: pd.Series, include_few_shots: bool = True) -> dict[str, Any]:
    messages = build_messages(row, include_few_shots=include_few_shots)
    response = deepseek_chat(messages)
    choice = response["choices"][0]
    content = choice["message"].get("content") or ""

    parsed: dict[str, Any] | None = None
    parse_error: str | None = None
    try:
        parsed = extract_json_object(content)
        parsed.setdefault("doc_id", clean_text(row.get("article_id")))
    except json.JSONDecodeError as e:
        # Keep raw_response/usage so malformed JSON can be inspected or repaired later.
        parse_error = repr(e)

    return {
        "article_id": clean_text(row.get("article_id")),
        "title": clean_text(row.get("title")),
        "content": clean_text(row.get("content")),
        "summary": clean_text(row.get("summary")),
        "label": parsed,
    }

# Nhập DeepSeek API key

In [4]:
import os
import getpass

os.environ.pop("DEEPSEEK_API_KEY", None)
os.environ["DEEPSEEK_API_KEY"] = getpass.getpass("Nhập lại DeepSeek API key: ").strip()

## Test 1 Article

Chạy cell này trước để xem API key, JSON mode, prompt và schema có ổn không. Để tránh gọi API ngoài ý muốn, mặc định `RUN_ONE_API_CALL = False`.

In [7]:
RUN_ONE_API_CALL = False

if RUN_ONE_API_CALL:
    one_result = label_one(df.iloc[0], include_few_shots=True)
    print(json.dumps(one_result["label"], ensure_ascii=False, indent=2))
    print("usage:", one_result["usage"])
else:
    print("Dry run only. Set RUN_ONE_API_CALL = True to call DeepSeek for the first article.")
    print(build_article_prompt(df.iloc[0])[:1200])

Dry run only. Set RUN_ONE_API_CALL = True to call DeepSeek for the first article.
Bây giờ hãy trích xuất bài báo sau theo đúng schema JSON trong system prompt.

Yêu cầu bắt buộc:
- Chỉ trả về JSON hợp lệ, không markdown, không giải thích.
- `doc_id` nếu cần thì dùng article_id bên dưới.
- Nếu không có sự kiện tài chính rõ ràng: events = [] và main_topic = "other".

article_id: 188251007222809692
source: cafef
category: Thị trường chứng khoán

TIÊU ĐỀ:
UBCKNN phát cảnh báo nóng đến những nhà đầu tư nộp tiền vào tài khoản chứng khoán này

TÓM TẮT:
UBCKNN khuyến cáo nhà đầu tư thận trọng, đồng thời kiểm tra, đối chiếu kỹ thông tin pháp lý trước khi mở tài khoản hay tham gia các hoạt động đầu tư để tránh bị lợi dụng, lừa đảo.

NỘI DUNG:
Ủy ban Chứng khoán Nhà nước (UBCKNN) vừa phát đi cảnh báo liên quan đến dấu hiệu giả mạo, lừa đảo mang tên Công ty TNHH Đầu tư Tư vấn STICCapital .
Theo UBCKNN, cơ quan này đã nhận được báo cáo từ Văn phòng đại diện Công ty đầu tư STIC Investments, Inc. tại Việt Nam, phản ánh việc một số nhà đầu tư bị hướng dẫn nạp tiền vào tài khoản chứng khoán mang tên Công ty TNHH Đầu tư Tư vấn STICCapital (số tài khoản 119003023002 tại Ngân hàng VietinBank).
Đáng chú ý, đối tượng còn thiết lập website tại địa chỉ https://sticinv.com và ứng dụng d

In [18]:
print(df.iloc[0]['content'] )

Ủy ban Chứng khoán Nhà nước (UBCKNN) vừa phát đi cảnh báo liên quan đến dấu hiệu giả mạo, lừa đảo mang tên Công ty TNHH Đầu tư Tư vấn STICCapital .
Theo UBCKNN, cơ quan này đã nhận được báo cáo từ Văn phòng đại diện Công ty đầu tư STIC Investments, Inc. tại Việt Nam, phản ánh việc một số nhà đầu tư bị hướng dẫn nạp tiền vào tài khoản chứng khoán mang tên Công ty TNHH Đầu tư Tư vấn STICCapital (số tài khoản 119003023002 tại Ngân hàng VietinBank).
Đáng chú ý, đối tượng còn thiết lập website tại địa chỉ https://sticinv.com và ứng dụng di động STCS Pro trên App Store và Google Play để tạo vỏ bọc hoạt động đầu tư hợp pháp.﻿
﻿UBCKNN khẳng định chưa từng cấp phép hoạt động hoặc bất kỳ giấy phép nào liên quan đến pháp nhân có tên Công ty TNHH Đầu tư Tư vấn STICCapital.
Cơ quan này khuyến cáo nhà đầu tư thận trọng, đồng thời kiểm tra, đối chiếu kỹ thông tin pháp lý trước khi mở tài khoản hay tham gia các hoạt động đầu tư để tránh bị lợi dụng, lừa đảo.

## Batch Label 10000 Rows

Output được append vào JSONL. Nếu notebook dừng giữa chừng, chạy lại cell này sẽ bỏ qua `article_id` đã có trong output.

In [5]:
def run_label_batch(start_row: int, end_row: int, run_batch: bool = True):
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    processed_ids: set[str] = set()

    # Chỉ skip các article_id đã label thành công. Các dòng lỗi sẽ được retry.
    if OUTPUT_PATH.exists():
        with OUTPUT_PATH.open("r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    record = json.loads(line)
                    if record.get("label") is not None and not record.get("error"):
                        processed_ids.add(str(record.get("article_id")))

    batch_df = df.iloc[start_row:end_row].copy()
    todo = batch_df.loc[~batch_df["article_id"].astype(str).isin(processed_ids)].copy()

    print("Output:", OUTPUT_PATH)
    print("Rows:", start_row, "to", end_row)
    print("Batch size:", len(batch_df))
    print("Already processed in this batch:", len(batch_df) - len(todo))
    print("Todo:", len(todo))

    if run_batch:
        with OUTPUT_PATH.open("a", encoding="utf-8") as out:
            for n, (_, row) in enumerate(todo.iterrows(), start=1):
                article_id = clean_text(row.get("article_id"))

                try:
                    result = label_one(row, include_few_shots=True)
                    result.setdefault("error", None)
                except Exception as e:
                    result = {
                        "article_id": article_id,
                        "title": clean_text(row.get("title")),
                        "published_date": clean_text(row.get("published_date")),
                        "url": clean_text(row.get("url")),
                        "label": None,
                        "raw_response": None,
                        "finish_reason": None,
                        "usage": {},
                        "model": MODEL,
                        "error": repr(e),
                    }

                out.write(json.dumps(result, ensure_ascii=False) + "\n")
                out.flush()

                if n % 10 == 0 or result.get("error"):
                    print(f"{n}/{len(todo)} article_id={article_id} error={result.get('error')}")

                time.sleep(REQUEST_SLEEP_SECONDS)
    else:
        print("Dry run only. Set run_batch=True to label this batch.")

In [27]:
run_label_batch(0, 1000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 0 to 1000
Batch size: 1000
Already processed in this batch: 238
Todo: 762
10/762 article_id=1200167 error=None
20/762 article_id=188250318210854194 error=None
30/762 article_id=188230910221303299 error=None
40/762 article_id=188250929200751963 error=None
50/762 article_id=188250521134226799 error=None
60/762 article_id=1279297 error=None
70/762 article_id=1376908 error=None
80/762 article_id=188251214182839882 error=None
90/762 article_id=188250603113356832 error=None
100/762 article_id=188250513221611983 error=None
110/762 article_id=188260507140145529 error=None
120/762 article_id=188241028113515356 error=None
130/762 article_id=188240914131717729 error=None
140/762 article_id=188231106081527028 error=None
150/762 article_id=188251211114020385 error=None
160/762 article_id=188240925181443482 error=None
170/762 article_id=188240718163620257 error=None
180/762 article_id=859736 error=None
190/762 article_id=188260224110348171 error=None
200/762 article_id=188260604080906032 error=None
210/762 article_id=1116299 error=None
220/762 article_id=188241129025519868 error=None
230/762 article_id=188240423090220082 error=None
240/762 article_id=188250605141134197 error=None
250/762 article_id=1363917 error=None
260/762 article_id=859159 error=None
270/762 article_id=188230925100950773 error=None
280/762 article_id=188240828132908722 error=None
290/762 article_id=1426695 error=None
300/762 article_id=188231009163851709 error=None
310/762 article_id=1157500 error=None
320/762 article_id=188260117095008818 error=None
330/762 article_id=1194343 error=None
340/762 article_id=1085965 error=None
350/762 article_id=188240907000758847 error=None
360/762 article_id=188260428072126045 error=None
370/762 article_id=188250408153857958 error=None
380/762 article_id=18824121115475513 error=None
390/762 article_id=1409942 error=None
400/762 article_id=188240309053146806 error=None
410/762 article_id=188240118163214892 error=None
420/762 article_id=991675 error=None
430/762 article_id=188240723185728229 error=None
440/762 article_id=188250618141309162 error=None
450/762 article_id=1327666 error=None
460/762 article_id=1110080 error=None
470/762 article_id=188250407235003841 error=None
480/762 article_id=188240425153208101 error=None
490/762 article_id=188250604224625502 error=None
500/762 article_id=188230907231208642 error=None
510/762 article_id=1072576 error=None
520/762 article_id=1387256 error=None
530/762 article_id=188251010124253886 error=None
540/762 article_id=1067168 error=None
550/762 article_id=188250318090141664 error=None
560/762 article_id=188250702103936845 error=None
570/762 article_id=1444872 error=None
580/762 article_id=188260310105112258 error=None
590/762 article_id=188251216105907559 error=None
600/762 article_id=188250926102906113 error=None
610/762 article_id=188240819165657877 error=None
620/762 article_id=188230927175647721 error=None
630/762 article_id=1217553 error=None
640/762 article_id=188240111111647614 error=None
650/762 article_id=911134 error=None
660/762 article_id=2023020722155367 error=None
670/762 article_id=188250225133120936 error=None
680/762 article_id=188250218172716249 error=None
690/762 article_id=188251217154632535 error=None
700/762 article_id=1242127 error=None
710/762 article_id=1194910 error=None
720/762 article_id=188251208182727108 error=None
730/762 article_id=188250622084856654 error=None
740/762 article_id=1081418 error=None
750/762 article_id=188250827140308326 error=None
760/762 article_id=999097 error=None

In [28]:
run_label_batch(1000, 2000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 1000 to 2000
Batch size: 1000
Already processed in this batch: 3
Todo: 997
10/997 article_id=188230828113526329 error=None
20/997 article_id=188250728031314636 error=None
30/997 article_id=820630 error=None
40/997 article_id=1052262 error=None
50/997 article_id=188251123215125451 error=None
60/997 article_id=1448917 error=None
70/997 article_id=188230511143405604 error=None
80/997 article_id=18826040119204519 error=None
90/997 article_id=188250506110310059 error=None
100/997 article_id=188241103195514793 error=None
110/997 article_id=188251105190041039 error=None
120/997 article_id=188260502204726838 error=None
130/997 article_id=1356480 error=None
140/997 article_id=820845 error=None
150/997 article_id=188250409121222994 error=None
160/997 article_id=188260128110608965 error=None
170/997 article_id=188250711110346618 error=None
180/997 article_id=188250427134550429 error=None
190/997 article_id=865644 error=None
200/997 article_id=188240120211023906 error=None
210/997 article_id=188240404171708138 error=None
220/997 article_id=188240830215105249 error=None
230/997 article_id=188240710111424601 error=None
240/997 article_id=188250421172139682 error=None
250/997 article_id=18826031617212633 error=None
260/997 article_id=188251230145512166 error=None
270/997 article_id=188240618154008846 error=None
280/997 article_id=188250302084726961 error=None
290/997 article_id=188240806171412499 error=None
300/997 article_id=188250806133823772 error=None
310/997 article_id=188260330134719486 error=None
320/997 article_id=188260329180340917 error=None
330/997 article_id=18824112717592929 error=None
340/997 article_id=188260519165539968 error=None
350/997 article_id=1229207 error=None
360/997 article_id=188231125160151673 error=None
370/997 article_id=188240612111957786 error=None
380/997 article_id=188241022205807275 error=None
390/997 article_id=188230329180149581 error=None
400/997 article_id=188241011192758969 error=None
410/997 article_id=188240724110139298 error=None
420/997 article_id=188260304103750925 error=None
430/997 article_id=188230913233550323 error=None
440/997 article_id=188250302232803489 error=None
450/997 article_id=20230207220622222 error=None
460/997 article_id=1401973 error=None
470/997 article_id=1421219 error=None
480/997 article_id=188230422193641701 error=None
490/997 article_id=902733 error=None
500/997 article_id=188250408230247187 error=None
510/997 article_id=188250726074354198 error=None
520/997 article_id=188251008232643981 error=None
530/997 article_id=840594 error=None
540/997 article_id=18824012522405599 error=None
550/997 article_id=188250618110831513 error=None
560/997 article_id=188251207230825968 error=None
570/997 article_id=188250701001406519 error=None
580/997 article_id=18825060514070032 error=None
590/997 article_id=188251030163239264 error=None
600/997 article_id=188240926150521659 error=None
610/997 article_id=188260424213042152 error=None
620/997 article_id=18824062817423719 error=None
630/997 article_id=18824080115122799 error=None
640/997 article_id=188251017153236804 error=None
650/997 article_id=1320343 error=None
660/997 article_id=188260130104937471 error=None
670/997 article_id=944899 error=None
680/997 article_id=1386021 error=None
690/997 article_id=188230824233758457 error=None
700/997 article_id=188230510155305433 error=None
710/997 article_id=1090749 error=None
720/997 article_id=884401 error=None
730/997 article_id=1127034 error=None
740/997 article_id=951848 error=None
750/997 article_id=1110494 error=None
760/997 article_id=188250203235642048 error=None
770/997 article_id=188260313102535159 error=None
780/997 article_id=188240913144224299 error=None
790/997 article_id=1436771 error=None
800/997 article_id=18825060222185741 error=None
810/997 article_id=1002872 error=None
820/997 article_id=1328820 error=None
830/997 article_id=188260411213223167 error=None
840/997 article_id=188230807181306066 error=None
850/997 article_id=188250405224217672 error=None
860/997 article_id=1124727 error=None
870/997 article_id=18824080316554098 error=None
880/997 article_id=188250203105013129 error=None
890/997 article_id=940824 error=None
900/997 article_id=1398358 error=None
910/997 article_id=1329242 error=None
920/997 article_id=188240625184023911 error=None
930/997 article_id=188260216125816466 error=None
940/997 article_id=188240221104813302 error=None
950/997 article_id=1100503 error=None
960/997 article_id=188241102220525074 error=None
970/997 article_id=18823050518494596 error=None
980/997 article_id=886300 error=None
990/997 article_id=188240617212418936 error=None

In [29]:
run_label_batch(2000, 3000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 2000 to 3000
Batch size: 1000
Already processed in this batch: 6
Todo: 994
10/994 article_id=188230910225358556 error=None
20/994 article_id=188230814134351172 error=None
30/994 article_id=1267918 error=None
40/994 article_id=188250616152710145 error=None
50/994 article_id=188240429170450375 error=None
60/994 article_id=1117620 error=None
70/994 article_id=188260506111705379 error=None
80/994 article_id=1237315 error=None
90/994 article_id=1369108 error=None
100/994 article_id=188240123111224833 error=None
110/994 article_id=1184923 error=None
120/994 article_id=1363904 error=None
121/994 article_id=188240129223735689 error=TimeoutError('The read operation timed out')
130/994 article_id=188250530113629549 error=None
140/994 article_id=188240509155033219 error=None
150/994 article_id=1882402162342353 error=None
160/994 article_id=869517 error=None
170/994 article_id=188250702225444365 error=None
180/994 article_id=188230726164700269 error=None
190/994 article_id=1174578 error=None
200/994 article_id=1011393 error=None
210/994 article_id=18826050515230689 error=None
220/994 article_id=18826022801223675 error=None
230/994 article_id=1228318 error=None
240/994 article_id=188240826095425273 error=None
250/994 article_id=1009538 error=None
260/994 article_id=18823052216214069 error=None
270/994 article_id=188241129150303768 error=None
280/994 article_id=1308845 error=None
290/994 article_id=1012123 error=None
300/994 article_id=188240622230240113 error=None
310/994 article_id=1234068 error=None
320/994 article_id=188240811092637197 error=None
330/994 article_id=18825062316363101 error=None
340/994 article_id=188250626123119861 error=None
350/994 article_id=188260312234838284 error=None
360/994 article_id=964154 error=None
370/994 article_id=1230675 error=None
380/994 article_id=1143970 error=None
390/994 article_id=1335913 error=None
400/994 article_id=188251123220618209 error=None
410/994 article_id=1020178 error=None
420/994 article_id=1271456 error=None
430/994 article_id=188250716104447668 error=None
440/994 article_id=18824122617373954 error=None
450/994 article_id=1112135 error=None
460/994 article_id=1312143 error=None
470/994 article_id=188230928225229338 error=None
480/994 article_id=871659 error=None
490/994 article_id=188260517173511394 error=None
500/994 article_id=188250114184724698 error=None
510/994 article_id=877707 error=None
520/994 article_id=188230608231304585 error=None
530/994 article_id=1031609 error=None
540/994 article_id=188250211235404092 error=None
550/994 article_id=1142481 error=None
560/994 article_id=188230329213114073 error=None
570/994 article_id=1117917 error=None
580/994 article_id=1156880 error=None
590/994 article_id=188240517101643513 error=None
600/994 article_id=188251110171542718 error=None
610/994 article_id=188260108200510177 error=None
620/994 article_id=1217644 error=None
630/994 article_id=20230102183504839 error=None
640/994 article_id=188230401094931828 error=None
650/994 article_id=188230516231200141 error=None
660/994 article_id=1062004 error=None
670/994 article_id=188251016173853172 error=None
680/994 article_id=188240506094346113 error=None
690/994 article_id=188260113102630431 error=None
700/994 article_id=188251119212554564 error=None
710/994 article_id=188260528234221534 error=None
720/994 article_id=188250408182039879 error=None
730/994 article_id=188230906230859568 error=None
740/994 article_id=188230509145100842 error=None
750/994 article_id=1041064 error=None
760/994 article_id=188230911090840867 error=None
770/994 article_id=1111380 error=None
780/994 article_id=18824090622261594 error=None
790/994 article_id=1423566 error=None
800/994 article_id=188250903171336612 error=None
810/994 article_id=873472 error=None
820/994 article_id=188230514110732949 error=None
830/994 article_id=188250123175106988 error=None
840/994 article_id=1245014 error=None
850/994 article_id=188231020085028176 error=None
860/994 article_id=1222597 error=None
870/994 article_id=1076457 error=None
880/994 article_id=188240224101326553 error=None
890/994 article_id=188230330174923332 error=None
900/994 article_id=188240609080450752 error=None
910/994 article_id=1375560 error=None
920/994 article_id=188241118224053467 error=None
930/994 article_id=188230627111524474 error=None
940/994 article_id=188260224144829327 error=None
950/994 article_id=18825111011172158 error=None
960/994 article_id=188251017231614278 error=None
970/994 article_id=1195026 error=None
980/994 article_id=18825010723192793 error=None
990/994 article_id=1106441 error=None

In [30]:
run_label_batch(3000, 4000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 3000 to 4000
Batch size: 1000
Already processed in this batch: 14
Todo: 986
10/986 article_id=188251017110741123 error=None
20/986 article_id=838807 error=None
30/986 article_id=892291 error=None
40/986 article_id=1222773 error=None
50/986 article_id=983251 error=None
60/986 article_id=1138327 error=None
70/986 article_id=188241016213559975 error=None
80/986 article_id=188240305152616248 error=None
90/986 article_id=188240804083447758 error=None
100/986 article_id=188241009141024262 error=None
110/986 article_id=188240829164301925 error=None
120/986 article_id=188240903213834599 error=None
130/986 article_id=188251022152524875 error=None
140/986 article_id=188240804161105757 error=None
150/986 article_id=20230217182933023 error=None
160/986 article_id=188260313193922121 error=None
170/986 article_id=188240416104803164 error=None
180/986 article_id=188250415220008569 error=None
190/986 article_id=188250127151921866 error=None
200/986 article_id=188240306145846788 error=None
210/986 article_id=188250402145349472 error=None
220/986 article_id=188240925152109461 error=None
230/986 article_id=188251209150056633 error=None
240/986 article_id=188251030224242428 error=None
250/986 article_id=188231013113248909 error=None
260/986 article_id=188240530151155748 error=None
270/986 article_id=1331250 error=None
280/986 article_id=1118854 error=None
290/986 article_id=188240409171427487 error=None
300/986 article_id=188251120210022131 error=None
310/986 article_id=188260524224603639 error=None
320/986 article_id=188240425100411856 error=None
330/986 article_id=188240320201353036 error=None
340/986 article_id=977166 error=None
350/986 article_id=188240927095042392 error=None
360/986 article_id=188250504105133209 error=None
370/986 article_id=1387231 error=None
380/986 article_id=18826012008083112 error=None
390/986 article_id=1324595 error=None
400/986 article_id=188251127191313841 error=None
410/986 article_id=188260203151111717 error=None
420/986 article_id=188240412121553979 error=None
430/986 article_id=188240831000256405 error=None
440/986 article_id=188260601221559975 error=None
450/986 article_id=1335628 error=None
460/986 article_id=188231204174637432 error=None
470/986 article_id=1085344 error=None
480/986 article_id=188241201150326451 error=None
490/986 article_id=1076573 error=None
500/986 article_id=18824110613482582 error=None
510/986 article_id=1023134 error=None
520/986 article_id=188240504084356776 error=None
530/986 article_id=18823102208531898 error=None
540/986 article_id=188250702225122933 error=None
550/986 article_id=188240821173615318 error=None
560/986 article_id=1213482 error=None
570/986 article_id=188241108234942163 error=None
580/986 article_id=1165231 error=None
590/986 article_id=188260317182141698 error=None
600/986 article_id=18824083115022791 error=None
610/986 article_id=1442308 error=None
620/986 article_id=188250415205434137 error=None
630/986 article_id=1019373 error=None
640/986 article_id=188231120090813758 error=None
650/986 article_id=188250728104658995 error=None
660/986 article_id=921123 error=None
670/986 article_id=188231004223631951 error=None
680/986 article_id=188251002180756334 error=None
690/986 article_id=1285100 error=None
700/986 article_id=18825012322552346 error=None
710/986 article_id=1139260 error=None
720/986 article_id=188240805205031369 error=None
730/986 article_id=188240104165317793 error=None
740/986 article_id=1232815 error=None
750/986 article_id=188231210201940424 error=None
760/986 article_id=188260304220809749 error=None
770/986 article_id=18825082622235386 error=None
780/986 article_id=188240724145506714 error=None
790/986 article_id=188241209131345013 error=None
800/986 article_id=188231017212657882 error=None
810/986 article_id=188250415132234167 error=None
820/986 article_id=188250218112428341 error=None
830/986 article_id=20230222101643188 error=None
840/986 article_id=1428608 error=None
850/986 article_id=1070285 error=None
860/986 article_id=188240916133512276 error=None
870/986 article_id=188240409103713599 error=None
880/986 article_id=188250321105104758 error=None
890/986 article_id=1168896 error=None
900/986 article_id=20230305222713788 error=None
910/986 article_id=1121954 error=None
920/986 article_id=1248070 error=None
930/986 article_id=188230615110320718 error=None
940/986 article_id=188260327122831143 error=None
950/986 article_id=188251001223132304 error=None
960/986 article_id=188241004122253707 error=None
970/986 article_id=1354052 error=None
980/986 article_id=188250819231347318 error=None

In [31]:
run_label_batch(4000, 5000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 4000 to 5000
Batch size: 1000
Already processed in this batch: 29
Todo: 971
10/971 article_id=852537 error=None
20/971 article_id=1019016 error=None
30/971 article_id=1050809 error=None
40/971 article_id=188260119222318398 error=None
50/971 article_id=188250611132019469 error=None
60/971 article_id=188251106165144208 error=None
70/971 article_id=1228314 error=None
80/971 article_id=886007 error=None
90/971 article_id=826757 error=None
100/971 article_id=188260319102640951 error=None
110/971 article_id=188240808225920582 error=None
120/971 article_id=950318 error=None
130/971 article_id=1201638 error=None
140/971 article_id=188250410145639046 error=None
150/971 article_id=188260519154458003 error=None
160/971 article_id=188230920065727469 error=None
170/971 article_id=188241017204313 error=None
180/971 article_id=188230701080927385 error=None
190/971 article_id=1059798 error=None
200/971 article_id=939056 error=None
210/971 article_id=188240503220542345 error=None
220/971 article_id=952904 error=None
230/971 article_id=868953 error=None
240/971 article_id=188251209145919923 error=None
250/971 article_id=993480 error=None
260/971 article_id=188260208215058269 error=None
270/971 article_id=1035493 error=None
280/971 article_id=1350718 error=None
290/971 article_id=188241115232922825 error=None
300/971 article_id=1284083 error=None
310/971 article_id=188260304110827974 error=None
320/971 article_id=1142779 error=None
330/971 article_id=188250618231741488 error=None
340/971 article_id=188240622110850864 error=None
350/971 article_id=1121703 error=None
360/971 article_id=188260310143703641 error=None
370/971 article_id=188240416230723727 error=None
380/971 article_id=188250804235956352 error=None
390/971 article_id=188260518142501181 error=None
400/971 article_id=188251002100600233 error=None
410/971 article_id=18823120717080004 error=None
420/971 article_id=188250409160131065 error=None
430/971 article_id=20230301211103646 error=None
440/971 article_id=188231023185816298 error=None
450/971 article_id=188251027105115572 error=None
460/971 article_id=188250719002507455 error=None
470/971 article_id=1012623 error=None
480/971 article_id=188250218193822308 error=None
490/971 article_id=1352601 error=None
500/971 article_id=188240924225211686 error=None
510/971 article_id=18826010611295345 error=None
520/971 article_id=1243712 error=None
530/971 article_id=188240831091611907 error=None
540/971 article_id=188241231225405973 error=None
550/971 article_id=188240228102631624 error=None
560/971 article_id=905206 error=None
570/971 article_id=188260304221224891 error=None
580/971 article_id=188250109150259776 error=None
590/971 article_id=824957 error=None
600/971 article_id=188240113081009761 error=None
610/971 article_id=188241024103507577 error=None
620/971 article_id=202301251222424 error=None
630/971 article_id=1215020 error=None
640/971 article_id=188260429173058651 error=None
650/971 article_id=858263 error=None
660/971 article_id=18826040522120508 error=None
670/971 article_id=1057807 error=None
680/971 article_id=823902 error=None
690/971 article_id=188240813152157983 error=None
700/971 article_id=1248039 error=None
710/971 article_id=188240416173639754 error=None
720/971 article_id=1174197 error=None
730/971 article_id=188250302153748429 error=None
740/971 article_id=1018095 error=None
750/971 article_id=817904 error=None
760/971 article_id=188241119210410354 error=None
770/971 article_id=822913 error=None
780/971 article_id=188250527120913209 error=None
790/971 article_id=952815 error=None
800/971 article_id=188240328212310953 error=None
810/971 article_id=1092994 error=None
820/971 article_id=188230801215250814 error=None
830/971 article_id=188250321220825944 error=None
840/971 article_id=188260528084800079 error=None
850/971 article_id=188241204121150592 error=None
860/971 article_id=188240227182234604 error=None
870/971 article_id=1256442 error=None
880/971 article_id=188240404160150928 error=None
890/971 article_id=1051883 error=None
900/971 article_id=188240723155245025 error=None
910/971 article_id=188260315143804416 error=None
920/971 article_id=188250922110020807 error=None
930/971 article_id=188251114233518849 error=None
940/971 article_id=1434656 error=None
950/971 article_id=855891 error=None
960/971 article_id=1358373 error=None
970/971 article_id=956838 error=None

In [32]:
run_label_batch(5000, 6000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 5000 to 6000
Batch size: 1000
Already processed in this batch: 18
Todo: 982
10/982 article_id=188250125120311734 error=None
20/982 article_id=188241017224805169 error=None
30/982 article_id=188230419102924236 error=None
40/982 article_id=1424001 error=None
50/982 article_id=1079204 error=None
60/982 article_id=188240821112106054 error=None
70/982 article_id=188260501174802923 error=None
80/982 article_id=18826050715390473 error=None
90/982 article_id=1197320 error=None
100/982 article_id=188260102001116598 error=None
110/982 article_id=1429122 error=None
120/982 article_id=188240801195127341 error=None
130/982 article_id=1253601 error=None
140/982 article_id=188240731005322419 error=None
150/982 article_id=188240104174124037 error=None
160/982 article_id=188241004163657023 error=None
170/982 article_id=188241016171151564 error=None
180/982 article_id=188250206113248431 error=None
190/982 article_id=188240809085759899 error=None
200/982 article_id=1212186 error=None
210/982 article_id=188250611234056381 error=None
220/982 article_id=188251120154102059 error=None
230/982 article_id=188240926180027214 error=None
240/982 article_id=188240221084801515 error=None
250/982 article_id=858388 error=None
260/982 article_id=188241028231147678 error=None
270/982 article_id=1110660 error=None
280/982 article_id=188250419003600154 error=None
290/982 article_id=1151583 error=None
300/982 article_id=188251019112250386 error=None
310/982 article_id=1336240 error=None
320/982 article_id=1272268 error=None
330/982 article_id=1418056 error=None
340/982 article_id=20230107103638681 error=None
350/982 article_id=1005152 error=None
360/982 article_id=188260214103735065 error=None
370/982 article_id=887003 error=None
380/982 article_id=188250203174116149 error=None
390/982 article_id=885640 error=None
400/982 article_id=188241220012629457 error=None
410/982 article_id=188230817102232942 error=None
420/982 article_id=1445902 error=None
430/982 article_id=188250507121512751 error=None
440/982 article_id=1116347 error=None
450/982 article_id=18824020220491265 error=None
460/982 article_id=188241001125903814 error=None
470/982 article_id=188260515234831986 error=None
480/982 article_id=1163124 error=None
490/982 article_id=188240330175212589 error=None
500/982 article_id=188251210140503583 error=None
510/982 article_id=828818 error=None
520/982 article_id=939708 error=None
530/982 article_id=188250804223635795 error=None
540/982 article_id=188240513181246425 error=None
550/982 article_id=188241005223108705 error=None
560/982 article_id=188231221002530769 error=None
570/982 article_id=852448 error=None
580/982 article_id=188230331113131032 error=None
590/982 article_id=188240325024504637 error=None
600/982 article_id=18824060922195089 error=None
610/982 article_id=188240228095930821 error=None
620/982 article_id=1295090 error=None
630/982 article_id=188251218085157463 error=None
640/982 article_id=188250403102136201 error=None
650/982 article_id=188241121175520515 error=None
660/982 article_id=188260330224257537 error=None
670/982 article_id=188241204134019335 error=None
680/982 article_id=188230505085930287 error=None
690/982 article_id=1446217 error=None
700/982 article_id=188230428154642405 error=None
710/982 article_id=1161614 error=None
720/982 article_id=188250912102647298 error=None
730/982 article_id=1265482 error=None
740/982 article_id=188250121150026377 error=None
750/982 article_id=188250702110221233 error=None
760/982 article_id=188240511095048304 error=None
770/982 article_id=18826040309023957 error=None
780/982 article_id=188240825091630469 error=None
790/982 article_id=188250109220810477 error=None
800/982 article_id=188250710205054728 error=None
810/982 article_id=1057131 error=None
820/982 article_id=188230920231613904 error=None
830/982 article_id=188240528203223549 error=None
840/982 article_id=859677 error=None
850/982 article_id=188230529154130241 error=None
860/982 article_id=188260528225614652 error=None
870/982 article_id=1116995 error=None
880/982 article_id=188250419181427858 error=None
890/982 article_id=188250324223546865 error=None
900/982 article_id=901723 error=None
910/982 article_id=1061424 error=None
920/982 article_id=1118544 error=None
930/982 article_id=1099275 error=None
940/982 article_id=1157178 error=None
950/982 article_id=188250907124643816 error=None
960/982 article_id=18825092315192241 error=None
970/982 article_id=18825031215215428 error=None
980/982 article_id=188260219094449281 error=None

In [33]:
run_label_batch(6000, 7000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 6000 to 7000
Batch size: 1000
Already processed in this batch: 23
Todo: 977
10/977 article_id=1242701 error=None
20/977 article_id=188260331175847365 error=None
30/977 article_id=188230922215704935 error=None
40/977 article_id=188231116131246417 error=None
50/977 article_id=1382106 error=None
60/977 article_id=1091277 error=None
70/977 article_id=910511 error=None
80/977 article_id=188260418095828416 error=None
90/977 article_id=188241116224737983 error=None
100/977 article_id=970691 error=None
110/977 article_id=188230605163737259 error=None
120/977 article_id=188240302093546337 error=None
125/977 article_id=188241108223728204 error=TimeoutError('The read operation timed out')
130/977 article_id=188230705094541409 error=None
140/977 article_id=188240909102556569 error=None
143/977 article_id=188260329073012567 error=TimeoutError('The read operation timed out')
150/977 article_id=1360000 error=None
160/977 article_id=20230216150314019 error=None
170/977 article_id=188250529232823928 error=None
180/977 article_id=1214248 error=None
190/977 article_id=188250913212546094 error=None
200/977 article_id=188250613170116918 error=None
210/977 article_id=188240719152916385 error=None
220/977 article_id=188250604171602865 error=None
230/977 article_id=188260508062048807 error=None
240/977 article_id=188250317222811355 error=None
250/977 article_id=18826051307253866 error=None
260/977 article_id=188230826224023452 error=None
270/977 article_id=188260526142449519 error=None
280/977 article_id=1115394 error=None
290/977 article_id=188260211105255394 error=None
300/977 article_id=188251209163738021 error=None
310/977 article_id=188231221221103506 error=None
320/977 article_id=188260316203707591 error=None
330/977 article_id=1336333 error=None
340/977 article_id=188241002141748896 error=None
350/977 article_id=949276 error=None
360/977 article_id=188240207095849931 error=None
370/977 article_id=1240178 error=None
380/977 article_id=20230215180051092 error=None
390/977 article_id=188251127114232832 error=None
400/977 article_id=870590 error=None
410/977 article_id=882530 error=None
420/977 article_id=188250410162318489 error=None
430/977 article_id=188230510140036166 error=None
440/977 article_id=188240922000613831 error=None
450/977 article_id=188250418183823536 error=None
460/977 article_id=1019645 error=None
470/977 article_id=1171451 error=None
480/977 article_id=188251106093020899 error=None
490/977 article_id=188260123230111504 error=None
500/977 article_id=1882304170731142 error=None
510/977 article_id=872052 error=None
520/977 article_id=188251126153121316 error=None
530/977 article_id=1079205 error=None
540/977 article_id=18824112408280557 error=None
550/977 article_id=20230119073634367 error=None
560/977 article_id=188251030102445295 error=None
570/977 article_id=188250326094340926 error=None
580/977 article_id=188230515162417967 error=None
590/977 article_id=188240910103039677 error=None
600/977 article_id=188260317140123214 error=None
610/977 article_id=188240509103342706 error=None
620/977 article_id=188230425224437247 error=None
630/977 article_id=188250914110436732 error=None
640/977 article_id=188250820184020587 error=None
650/977 article_id=188260507163603257 error=None
660/977 article_id=188251117163138422 error=None
670/977 article_id=947959 error=None
680/977 article_id=188250214150355575 error=None
690/977 article_id=830717 error=None
700/977 article_id=188230915134059455 error=None
710/977 article_id=1142568 error=None
720/977 article_id=873978 error=None
730/977 article_id=188241003142118909 error=None
740/977 article_id=20230215112207544 error=None
750/977 article_id=993767 error=None
760/977 article_id=188241014223901228 error=None
770/977 article_id=188250119204647983 error=None
780/977 article_id=819319 error=None
790/977 article_id=885306 error=None
800/977 article_id=1147633 error=None
810/977 article_id=1076713 error=None
820/977 article_id=841321 error=None
830/977 article_id=188250123165219998 error=None
840/977 article_id=188250617000120261 error=None
850/977 article_id=188250705094336622 error=None
860/977 article_id=188240604174736233 error=None
870/977 article_id=188251001173347267 error=None
880/977 article_id=188250320152449702 error=None
890/977 article_id=188231030130654516 error=None
900/977 article_id=188250624111815374 error=None
910/977 article_id=18825041623544551 error=None
920/977 article_id=1059930 error=None
930/977 article_id=1226068 error=None
940/977 article_id=188250703140830192 error=None
950/977 article_id=188250615001712694 error=None
960/977 article_id=1181258 error=None
970/977 article_id=188250930105556152 error=None

In [36]:
run_label_batch(7000, 8000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 7000 to 8000
Batch size: 1000
Already processed in this batch: 705
Todo: 295
10/295 article_id=188260315223043196 error=None
20/295 article_id=897637 error=None
30/295 article_id=188250609232712135 error=None
40/295 article_id=188241029230449532 error=None
50/295 article_id=1256563 error=None
60/295 article_id=188240506105146739 error=None
70/295 article_id=18826010210403313 error=None
80/295 article_id=1403420 error=None
90/295 article_id=188250409132431325 error=None
100/295 article_id=188251015173251102 error=None
110/295 article_id=188260305225734491 error=None
120/295 article_id=188230630180326254 error=None
130/295 article_id=970529 error=None
140/295 article_id=1102485 error=None
150/295 article_id=188240827104913054 error=None
160/295 article_id=1156322 error=None
170/295 article_id=1278197 error=None
180/295 article_id=188250925225029607 error=None
190/295 article_id=188250116233413091 error=None
200/295 article_id=188240923234138806 error=None
210/295 article_id=1040534 error=None
214/295 article_id=1122667 error=TimeoutError('The read operation timed out')
220/295 article_id=188240729140842109 error=None
230/295 article_id=188241017225357069 error=TimeoutError('The read operation timed out')
240/295 article_id=849255 error=None
250/295 article_id=1150710 error=None
260/295 article_id=188251231102033771 error=None
270/295 article_id=188230923152726725 error=None
280/295 article_id=188240827111934493 error=None
290/295 article_id=188241024094721238 error=None

In [37]:
run_label_batch(8000, 9000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 8000 to 9000
Batch size: 1000
Already processed in this batch: 33
Todo: 967
10/967 article_id=188240224124823873 error=None
20/967 article_id=188251206182034115 error=None
30/967 article_id=188260421105753333 error=None
40/967 article_id=188230925100108365 error=None
50/967 article_id=18826020621494972 error=None
60/967 article_id=880741 error=None
70/967 article_id=188230629163519707 error=None
80/967 article_id=188250512090854405 error=None
90/967 article_id=1117548 error=None
100/967 article_id=188230810085853059 error=None
110/967 article_id=1294406 error=None
120/967 article_id=917689 error=None
130/967 article_id=18823102609460303 error=None
140/967 article_id=974386 error=None
150/967 article_id=188251215182017134 error=None
160/967 article_id=188251026081030992 error=None
170/967 article_id=188230918090042549 error=None
180/967 article_id=828552 error=None
190/967 article_id=1283955 error=None
200/967 article_id=20230313231948541 error=None
210/967 article_id=188250611233808753 error=None
220/967 article_id=936385 error=None
230/967 article_id=188250903132927359 error=None
240/967 article_id=188251027000829461 error=None
250/967 article_id=1393113 error=None
260/967 article_id=20230228154114581 error=None
270/967 article_id=188240910124218732 error=None
280/967 article_id=1422686 error=None
290/967 article_id=188260513145031724 error=None
300/967 article_id=188251116230503248 error=None
310/967 article_id=1118721 error=None
320/967 article_id=188230329154232076 error=None
330/967 article_id=1159448 error=None
340/967 article_id=1066998 error=None
350/967 article_id=891218 error=None
360/967 article_id=188240110173603077 error=None
370/967 article_id=18823040120314433 error=None
380/967 article_id=1435203 error=None
390/967 article_id=188251213213005847 error=None
400/967 article_id=1074976 error=None
410/967 article_id=188230912102730845 error=None
420/967 article_id=1229397 error=None
430/967 article_id=865794 error=None
440/967 article_id=188251128101920925 error=None
450/967 article_id=188250202105238259 error=None
460/967 article_id=1029502 error=None
470/967 article_id=188250214103721074 error=None
480/967 article_id=1272041 error=None
490/967 article_id=188251016153418163 error=None
500/967 article_id=959113 error=None
510/967 article_id=188240829171039285 error=None
520/967 article_id=188240123190519729 error=None
530/967 article_id=188260601221925615 error=None
540/967 article_id=959987 error=None
550/967 article_id=1449041 error=None
560/967 article_id=1072188 error=None
570/967 article_id=18823072015073315 error=None
580/967 article_id=188250325111302474 error=None
590/967 article_id=1201223 error=None
600/967 article_id=188260406224550681 error=None
610/967 article_id=188240629131511794 error=None
620/967 article_id=188250423221018759 error=None
630/967 article_id=188240923154853793 error=None
640/967 article_id=188230615105505793 error=None
650/967 article_id=188260310153256081 error=None
660/967 article_id=188260409200102647 error=None
670/967 article_id=882115 error=None
680/967 article_id=188250714125156801 error=None
690/967 article_id=188241202151918931 error=None
700/967 article_id=188240124141653662 error=None
710/967 article_id=953014 error=None
720/967 article_id=1172628 error=None
730/967 article_id=188260119142724723 error=None
740/967 article_id=1137586 error=None
750/967 article_id=20230118172959877 error=None
760/967 article_id=188250725232539184 error=None
770/967 article_id=20230301102439253 error=None
780/967 article_id=18825111709151975 error=None
790/967 article_id=188250816175615868 error=None
800/967 article_id=20230321233459121 error=None
810/967 article_id=1245488 error=None
820/967 article_id=188250820140912182 error=None
830/967 article_id=188240719105719838 error=None
840/967 article_id=188241118223937503 error=None
850/967 article_id=188241030121829371 error=None
860/967 article_id=188250815103734145 error=None
870/967 article_id=188241126152155235 error=None
880/967 article_id=188250615233313203 error=None
890/967 article_id=188240913152959827 error=None
900/967 article_id=188260421151137231 error=None
910/967 article_id=188230629153853435 error=None
920/967 article_id=1105363 error=None
930/967 article_id=1285488 error=None
940/967 article_id=188251223150318208 error=None
950/967 article_id=1341710 error=None
960/967 article_id=1882604281457457 error=None

In [10]:
run_label_batch(9000, 10000, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 9000 to 10000
Batch size: 1000
Already processed in this batch: 998
Todo: 2

In [11]:
run_label_batch(9000, 9500, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 9000 to 9500
Batch size: 500
Already processed in this batch: 499
Todo: 1

In [15]:
run_label_batch(10000, 10500, run_batch=True)

Output: /Users/buithianhdao/SE365/data/processed/10k_labeled_news.jsonl
Rows: 10000 to 10500
Batch size: 500
Already processed in this batch: 22
Todo: 478
10/478 article_id=188260402145120997 error=None
20/478 article_id=188230411221842214 error=None
30/478 article_id=1024552 error=None
40/478 article_id=18824021322565935 error=None
50/478 article_id=188260130151735162 error=None
60/478 article_id=188240620010719361 error=None
70/478 article_id=851987 error=None
80/478 article_id=188250417164542254 error=None
90/478 article_id=188240316121336671 error=None
100/478 article_id=188230409120117759 error=None
110/478 article_id=188250625173419872 error=None
120/478 article_id=1882404251005284 error=None
130/478 article_id=188260402004502767 error=None
140/478 article_id=1003831 error=None
150/478 article_id=188231128233143633 error=None
160/478 article_id=188241205204807422 error=None
170/478 article_id=188230814155010245 error=None
180/478 article_id=188250217101624342 error=None
190/478 article_id=1003835 error=None
200/478 article_id=188260403232134773 error=None

KeyboardInterrupt:

## Inspect Results And Cost Tokens

In [9]:
def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


records = load_jsonl(OUTPUT_PATH)
print("records:", len(records))
if records:
    result_df = pd.DataFrame(records)
    result_df["raw_response_chars"] = result_df["raw_response"].apply(lambda x: len(x) if isinstance(x, str) else 0)
    display(result_df[["article_id", "title", "published_date", "error", "finish_reason", "raw_response_chars"]].head(20))

    usage = pd.json_normalize([r.get("usage", {}) for r in records])
    if not usage.empty:
        print(usage.sum(numeric_only=True).to_string())

    labels = [r.get("label") for r in records if r.get("label")]
    event_counts = {}
    for label in labels:
        for event in label.get("events", []) or []:
            event_type = event.get("event_type")
            event_counts[event_type] = event_counts.get(event_type, 0) + 1
    print("event_counts:")
    print(json.dumps(dict(sorted(event_counts.items(), key=lambda x: str(x[0]))), ensure_ascii=False, indent=2))

records: 1000

,article_id,title,published_date,error,finish_reason,raw_response_chars
0,188231229103257892,"Thủy điện Hủa Na (HNA) ước lãi 217 tỷ đồng, lê...",2023-12-29,None,stop,2695
1,188231229094645055,Hành trình 16 năm và những dấu ấn tiên phong c...,2023-12-29,None,stop,750
2,188231229082554747,"UBCKNN xử phạt Công ty Đại Nam của ông Dũng ""L...",2023-12-29,None,stop,1797
3,188231228162951823,Từng gây chấn động với giá gần 1 triệu đồng/cp...,2023-12-29,None,stop,3582
4,188231228183151294,Góc nhìn CTCK: Rung lắc có thể sớm xuất hiện k...,2023-12-28,None,stop,1831
5,18823122817101572,"Cùng chiều khối ngoại, tự doanh CTCK mua ròng ...",2023-12-28,None,stop,3122
6,188231228165707197,Cổ phiếu nhà Vingroup tiếp tục gây chú ý,2023-12-28,None,stop,5124
7,188231228164957233,Hãng dược hơn trăm tuổi Nhật Bản tung 200 tỷ m...,2023-12-28,None,stop,3003
8,18823122815555081,Khối ngoại tiếp đà mua ròng 330 tỷ đồng trong ...,2023-12-28,None,stop,16297
9,188231228133628241,Cổ phiếu của một công ty vốn nghìn tỷ bị huỷ n...,2023-12-28,None,stop,1762
10,188231228125753636,Chứng khoán 2023: Bước đệm cho hành trình nâng...,2023-12-28,None,stop,12660
11,188231228113546171,"Dự báo VN-Index lên 1.460 điểm trong năm 2024,...",2023-12-28,None,stop,2423
12,188231228105806736,"""Đến hẹn lại lên"", Đạm Cà Mau (DCM) năm thứ ba...",2023-12-28,None,stop,3446
13,188231227165513427,Bật mí “chiến lược” VPBankS: Trở thành One-Sto...,2023-12-28,None,stop,731
14,188231227163609233,Lịch sự kiện và tin vắn chứng khoán ngày 28/12,2023-12-28,None,stop,16958
15,188231227172408388,Một nhóm ngành được dự báo tăng trưởng lợi nhu...,2023-12-28,None,stop,1196
16,188231227210317595,"Trái phiếu doanh nghiệp, bảo hiểm... ế",2023-12-27,None,stop,4848
17,188231227210010218,Cổ phiếu Vinhomes xuất hiện giao dịch lớn nhất...,2023-12-27,None,stop,2780
18,188231227191807944,Góc nhìn CTCK: VN-Index có thể sớm gặp áp lực ...,2023-12-27,None,stop,1709
19,188231227185121636,Phiên 27/12: Tự doanh CTCK mua ròng 400 tỷ trê...,2023-12-27,None,stop,4929

prompt_tokens                          10531217
completion_tokens                       1426644
total_tokens                           11957861
prompt_cache_hit_tokens                 9181184
prompt_cache_miss_tokens                1350033
prompt_tokens_details.cached_tokens     9181184
event_counts:
{
  "declare_bankruptcy": 6,
  "dividend": 270,
  "earnings_report": 399,
  "equity_freeze": 7,
  "equity_overweight": 236,
  "equity_repurchase": 9,
  "equity_underweight": 311,
  "lawsuit": 20,
  "legal_penalty": 110,
  "macro_indicator": 145,
  "merge_org": 12,
  "other": 36,
  "personnel_change": 76,
  "price_movement": 999,
  "share_issuance": 209,
  "transfer_money": 47,
  "transfer_ownership": 60
}

## Inspect Raw Response For Failed Articles

Sau khi batch chạy, dùng helper này để in `raw_response` của một `article_id`, nhất là các dòng bị `JSONDecodeError`.

In [11]:
import re


def show_raw_response(article_id: str, *, full: bool = False, context_chars: int = 1200) -> None:
    records = load_jsonl(OUTPUT_PATH)
    matches = [r for r in records if str(r.get("article_id")) == str(article_id)]
    print("matches:", len(matches))
    if not matches:
        return

    for idx, record in enumerate(matches, start=1):
        raw = record.get("raw_response")
        error = record.get("error")
        print("\n--- match", idx, "---")
        print("title:", record.get("title"))
        print("error:", error)
        print("finish_reason:", record.get("finish_reason"))
        print("usage:", record.get("usage"))
        print("raw_response_chars:", len(raw) if isinstance(raw, str) else None)

        if not isinstance(raw, str):
            print("raw_response is None. Record này có thể được tạo trước khi sửa notebook; hãy chạy lại batch cho article này.")
            continue

        if full:
            print(raw)
            continue

        match = re.search(r"char (\d+)", str(error))
        if match:
            pos = int(match.group(1))
            start = max(0, pos - context_chars)
            end = min(len(raw), pos + context_chars)
            print(f"showing raw_response[{start}:{end}] around char {pos}:")
            print(raw[start:end])
        else:
            print(f"showing raw_response[:{context_chars}]:")
            print(raw[:context_chars])


# Example:
show_raw_response("188231220091258805")
show_raw_response("188231220091258805", full=True)

matches: 1

--- match 1 ---
title: Lịch sự kiện và tin vắn chứng khoán ngày 20/12
error: None
finish_reason: stop
usage: {'prompt_tokens': 10496, 'completion_tokens': 4903, 'total_tokens': 15399, 'prompt_tokens_details': {'cached_tokens': 10368}, 'prompt_cache_hit_tokens': 10368, 'prompt_cache_miss_tokens': 128}
raw_response_chars: 13559
showing raw_response[:1200]:
{
  "doc_id": "188231220091258805",
  "language": "vi",
  "main_topic": "ownership_change",
  "entities": [
    {"name": "PYN ELITE FUND (NON-UCITS)", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn", "type": "Company", "ticker": "SCS", "role_in_article": "mentioned"},
    {"name": "CT TNHH Sài Gòn 3 Jean", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Pin Ắc quy miền Nam", "type": "Company", "ticker": "PAC", "role_in_article": "mentioned"},
    {"name": "Nguyễn Thị Nga", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP SAMETEL", "type": "Company", "ticker": "SMT", "role_in_article": "mentioned"},
    {"name": "Trương Huy Tâm", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP Tập đoàn VEXILLA Việt Nam", "type": "Company", "ticker": "SVN", "role_in_article": "mentioned"},
    {"name": "Võ Thiên Chương", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Trang", "type": "Company", "ticker": "TFC", "role_in_article": "mentioned"},
    {"name"
matches: 1

--- match 1 ---
title: Lịch sự kiện và tin vắn chứng khoán ngày 20/12
error: None
finish_reason: stop
usage: {'prompt_tokens': 10496, 'completion_tokens': 4903, 'total_tokens': 15399, 'prompt_tokens_details': {'cached_tokens': 10368}, 'prompt_cache_hit_tokens': 10368, 'prompt_cache_miss_tokens': 128}
raw_response_chars: 13559
{
  "doc_id": "188231220091258805",
  "language": "vi",
  "main_topic": "ownership_change",
  "entities": [
    {"name": "PYN ELITE FUND (NON-UCITS)", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn", "type": "Company", "ticker": "SCS", "role_in_article": "mentioned"},
    {"name": "CT TNHH Sài Gòn 3 Jean", "type": "Organization", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Pin Ắc quy miền Nam", "type": "Company", "ticker": "PAC", "role_in_article": "mentioned"},
    {"name": "Nguyễn Thị Nga", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP SAMETEL", "type": "Company", "ticker": "SMT", "role_in_article": "mentioned"},
    {"name": "Trương Huy Tâm", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP Tập đoàn VEXILLA Việt Nam", "type": "Company", "ticker": "SVN", "role_in_article": "mentioned"},
    {"name": "Võ Thiên Chương", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "Công ty Cổ phần Trang", "type": "Company", "ticker": "TFC", "role_in_article": "mentioned"},
    {"name": "Lê Thị Hồng Hạnh", "type": "Person", "ticker": null, "role_in_article": "subject"},
    {"name": "CTCP Bảo hiểm Ngân hàng Nông Nghiệp", "type": "Company", "ticker": "ABI", "role_in_article": "mentioned"},
    {"name": "Vũ Thúy Hạnh", "type": "Person", "ticker": null, "role_in_article": "subject"}
  ],
  "events": [
    {
      "event_type": "equity_underweight",
      "entities_involved": ["PYN ELITE FUND (NON-UCITS)", "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn"],
      "context": {
        "who": "PYN ELITE FUND (NON-UCITS)",
        "what": "Bán 200.000 cổ phiếu SCS",
        "when": "14/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là gần 5,5 triệu cổ phiếu (5,8% vốn)"
      },
      "attributes": {
        "equity_holder": "PYN ELITE FUND (NON-UCITS)",
        "traded_shares": 200000,
        "start_date": "2023-12-14",
        "end_date": "2023-12-14",
        "average_price": null,
        "later_holding_shares": 5500000
      },
      "evidence_text": "PYN ELITE FUND (NON-UCITS) đã bán 200.000 cổ phiếu SCS. Số lượng cổ phiếu nắm giữ sau khi thực hiện giao dịch là gần 5,5 triệu cổ phiếu tương ứng 5,8% vốn.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["CT TNHH Sài Gòn 3 Jean", "Công ty Cổ phần Pin Ắc quy miền Nam"],
      "context": {
        "who": "CT TNHH Sài Gòn 3 Jean",
        "what": "Mua 3 triệu cổ phiếu PAC",
        "when": "14/12/2023 - 15/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là 3 triệu cổ phiếu (6,46% vốn)"
      },
      "attributes": {
        "equity_holder": "CT TNHH Sài Gòn 3 Jean",
        "trading_shares": 3000000,
        "date": "14/12/2023 - 15/12/2023",
        "later_holding_shares": 3000000,
        "later_holding_pct": 6.46,
        "average_price": null
      },
      "evidence_text": "CT TNHH Sài Gòn 3 Jean đã mua 3 triệu cổ phiếu PAC, tăng sở hữu lên 3 triệu cổ phiếu, tỷ lệ 6,46%.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Nguyễn Thị Nga", "CTCP SAMETEL"],
      "context": {
        "who": "Nguyễn Thị Nga",
        "what": "Mua 139.200 cổ phiếu SMT",
        "when": "13/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là 528.200 cổ phiếu (9,66% vốn)"
      },
      "attributes": {
        "equity_holder": "Nguyễn Thị Nga",
        "trading_shares": 139200,
        "date": "13/12/2023",
        "later_holding_shares": 528200,
        "later_holding_pct": 9.66,
        "average_price": null
      },
      "evidence_text": "Cổ đông lớn Nguyễn Thị Nga đã mua 139.200 cổ phiếu SMT. Số lượng cổ phiếu nắm giữ sau khi thực hiện giao dịch là 528.200 cổ phiếu (tỷ lệ 9,66%).",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Trương Huy Tâm", "CTCP Tập đoàn VEXILLA Việt Nam"],
      "context": {
        "who": "Trương Huy Tâm",
        "what": "Mua 649.900 cổ phiếu SVN",
        "when": "7/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "completed",
        "result": "Số lượng nắm giữ sau giao dịch là 1.269.900 cổ phiếu (6,05% vốn)"
      },
      "attributes": {
        "equity_holder": "Trương Huy Tâm",
        "trading_shares": 649900,
        "date": "7/12/2023",
        "later_holding_shares": 1269900,
        "later_holding_pct": 6.05,
        "average_price": null
      },
      "evidence_text": "Cổ đông lớn Trương Huy Tâm đã mua 649.900 cổ phiếu SVN. Số lượng cổ phiếu nắm giữ sau khi thực hiện giao dịch là 1.269.900 cổ phiếu (tỷ lệ 6,05%).",
      "confidence": 0.95
    },
    {
      "event_type": "equity_underweight",
      "entities_involved": ["Võ Thiên Chương", "Công ty Cổ phần Trang"],
      "context": {
        "who": "Võ Thiên Chương",
        "what": "Đăng ký bán 200.000 cổ phiếu TFC",
        "when": "21/12/2023 - 18/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "equity_holder": "Võ Thiên Chương",
        "traded_shares": 200000,
        "start_date": "2023-12-21",
        "end_date": "2024-01-18",
        "average_price": null,
        "later_holding_shares": null
      },
      "evidence_text": "Ủy viên HĐQT Võ Thiên Chương đăng ký bán 200.000 cổ phiếu TFC. Thời gian giao dịch dự kiến từ 21/12/2023 đến 18/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Lê Thị Hồng Hạnh", "CTCP Bảo hiểm Ngân hàng Nông Nghiệp"],
      "context": {
        "who": "Lê Thị Hồng Hạnh",
        "what": "Đăng ký mua 120.000 cổ phiếu ABI",
        "when": "22/12/2023 - 19/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "equity_holder": "Lê Thị Hồng Hạnh",
        "trading_shares": 120000,
        "date": "22/12/2023 - 19/1/2024",
        "later_holding_shares": null,
        "later_holding_pct": null,
        "average_price": null
      },
      "evidence_text": "Bà Lê Thị Hồng Hạnh đăng ký mua 120.000 cổ phiếu ABI. Thời gian giao dịch dự kiến từ 22/12/2023 đến 19/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "equity_overweight",
      "entities_involved": ["Vũ Thúy Hạnh", "CTCP Bảo hiểm Ngân hàng Nông Nghiệp"],
      "context": {
        "who": "Vũ Thúy Hạnh",
        "what": "Đăng ký mua 200.000 cổ phiếu ABI",
        "when": "21/12/2023 - 29/12/2023",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "equity_holder": "Vũ Thúy Hạnh",
        "trading_shares": 200000,
        "date": "21/12/2023 - 29/12/2023",
        "later_holding_shares": null,
        "later_holding_pct": null,
        "average_price": null
      },
      "evidence_text": "Bà Vũ Thúy Hạnh đăng ký mua 200.000 cổ phiếu ABI. Thời gian giao dịch dự kiến từ 21/12/2023 đến 29/12/2023.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh"],
      "context": {
        "who": "Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh",
        "what": "Tạm ứng cổ tức năm 2023 bằng tiền mặt tổng tỷ lệ 30%",
        "when": "Ngày đăng ký cuối cùng 29/12/2023, chi trả đợt 1 ngày 31/1/2024, đợt 2 ngày 22/3/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 30,
        "dividend_per_share": {"value": 3000, "unit": "VND/share"},
        "ex_date": "2023-12-29",
        "payment_date": "2024-01-31",
        "total_amount": null
      },
      "evidence_text": "Ngày 29/12 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận tạm ứng cổ tức năm 2023 bằng tiền mặt tổng tỷ lệ 30% (tương ứng mỗi cổ phiếu nhận về 3.000 đồng). VSH dự kiến chi trả đợt 1 (10%) vào 31/1/2024 và đợt 2 (20%) vào 22/3/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["Công ty Cổ phần Nhiên liệu Sài Gòn"],
      "context": {
        "who": "Công ty Cổ phần Nhiên liệu Sài Gòn",
        "what": "Chi trả cổ tức năm 2023 bằng tiền mặt tỷ lệ 20%",
        "when": "Ngày đăng ký cuối cùng 19/1/2024, chi trả ngày 24/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 20,
        "dividend_per_share": {"value": 2000, "unit": "VND/share"},
        "ex_date": "2024-01-19",
        "payment_date": "2024-01-24",
        "total_amount": null
      },
      "evidence_text": "Ngày 19/1/2024 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận cổ tức năm 2023 bằng tiền mặt tỷ lệ 20% (tương ứng mỗi cổ phiếu nhận về 2.000 đồng). SFC dự kiến chi trả vào 24/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["CTCP Que hàn điện Việt Đức"],
      "context": {
        "who": "CTCP Que hàn điện Việt Đức",
        "what": "Chi trả cổ tức năm 2023 bằng tiền mặt tỷ lệ 20%",
        "when": "Ngày đăng ký cuối cùng 29/12/2023, chi trả ngày 22/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 20,
        "dividend_per_share": {"value": 2000, "unit": "VND/share"},
        "ex_date": "2023-12-29",
        "payment_date": "2024-01-22",
        "total_amount": null
      },
      "evidence_text": "Ngày 29/12 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận cổ tức năm 2023 bằng tiền mặt tỷ lệ 20% (tương ứng mỗi cổ phiếu nhận về 2.000 đồng). QHD dự kiến chi trả vào 22/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "dividend",
      "entities_involved": ["CTCP Vật liệu Xây dựng và Trang trí Nội thất Thành phố Hồ Chí Minh"],
      "context": {
        "who": "CTCP Vật liệu Xây dựng và Trang trí Nội thất Thành phố Hồ Chí Minh",
        "what": "Chi trả cổ tức năm 2023 bằng tiền mặt tỷ lệ 20%",
        "when": "Ngày đăng ký cuối cùng 12/1/2024, chi trả ngày 25/1/2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "dividend_type": "cash",
        "dividend_rate_pct": 20,
        "dividend_per_share": {"value": 2000, "unit": "VND/share"},
        "ex_date": "2024-01-12",
        "payment_date": "2024-01-25",
        "total_amount": null
      },
      "evidence_text": "Ngày 12/1/2024 là ngày đăng ký cuối cùng để chốt danh sách cổ đông nhận cổ tức năm 2023 bằng tiền mặt tỷ lệ 20% (tương ứng mỗi cổ phiếu nhận về 2.000 đồng). CMD dự kiến chi trả vào 25/1/2024.",
      "confidence": 0.95
    },
    {
      "event_type": "transfer_ownership",
      "entities_involved": ["Công ty Cổ phần Xuất Nhập Khẩu An Giang", "CTCP The Golden Group"],
      "context": {
        "who": "Công ty Cổ phần Xuất Nhập Khẩu An Giang",
        "what": "Chuyển nhượng 21% vốn góp tại AGM Furious cho CTCP The Golden Group",
        "when": null,
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "transferor": "Công ty Cổ phần Xuất Nhập Khẩu An Giang",
        "transferee": "CTCP The Golden Group",
        "asset_description": "21% vốn góp tại AGM Furious",
        "value": null,
        "stake_pct": 21
      },
      "evidence_text": "Thông báo Nghị quyết HĐQT về việc chuyển nhượng 21% vốn góp tại AGM Furious cho CTCP The Golden Group.",
      "confidence": 0.9
    },
    {
      "event_type": "earnings_report",
      "entities_involved": ["Công ty Cổ phần Phân bón Dầu khí Cà Mau"],
      "context": {
        "who": "Công ty Cổ phần Phân bón Dầu khí Cà Mau",
        "what": "Công bố kế hoạch SXKD năm 2024",
        "when": "năm 2024",
        "where": null,
        "why": null,
        "how": null,
        "tense": "planned",
        "result": null
      },
      "attributes": {
        "period": "năm 2024",
        "revenue": {"value": 11878, "unit": "tỷ VND", "yoy_change_pct": null},
        "net_profit": {"value": 795, "unit": "tỷ VND", "yoy_change_pct": null},
        "eps": null,
        "vs_forecast": null
      },
      "evidence_text": "Thông báo các chỉ tiêu kế hoạch hoạt động SXKD chính năm 2024, trong đó kế hoạch tổng doanh thu hợp nhất 11.878 tỷ và LNST 795 tỷ đồng.",
      "confidence": 0.95
    }
  ],
  "summary": "Tổng hợp tin vắn chứng khoán ngày 20/12: giao dịch cổ đông lớn tại SCS, PAC, SMT, SVN; đăng ký giao dịch tại TFC, ABI; cổ tức tiền mặt tại VSH, SFC, QHD, CMD; chuyển nhượng vốn tại AGM; kế hoạch kinh doanh 2024 của DCM."
}