In [29]:
pip install finrl vnstock stable-baselines3 pyfolio-reloaded quantstats

Requirement already satisfied: finrl in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.3.7)
Requirement already satisfied: vnstock in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (4.0.4)
Requirement already satisfied: stable-baselines3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.4.0)
Requirement already satisfied: pyfolio-reloaded in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.9.9)
Requirement already satisfied: quantstats in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.0.81)
Requirement already satisfied: requests in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from vnstock) (2.34.2)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (4.12.3)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (2.2.3)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (0.13.2)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (3.1.5)
Requirement already satisfied: pydantic in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (2.12.5)
Requirement already satisfied: psutil in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (7.2.2)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (24.2)
Requirement already satisfied: importlib-metadata>=1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (8.7.1)
Requirement already satisfied: tenacity in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (8.5.0)
Requirement already satisfied: vnai>=2.4.8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (2.4.8)
Requirement already satisfied: vnstock_ezchart>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (1.0.2)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock) (2023.4)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stable-baselines3) (1.0.0)
Requirement already satisfied: numpy<2.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stable-baselines3) (1.26.4)
Requirement already satisfied: torch>=1.13 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stable-baselines3) (2.5.1)
Requirement already satisfied: cloudpickle in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stable-baselines3) (3.1.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stable-baselines3) (3.9.2)
Requirement already satisfied: typing-extensions>=4.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3) (0.0.4)
Requirement already satisfied: ipython>=3.2.3 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pyfolio-reloaded) (8.27.0)
Requirement already satisfied: scipy>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pyfolio-reloaded) (1.15.2)
Requirement already satisfied: scikit-learn>=0.16.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pyfolio-reloaded) (1.8.0)
Requirement already satisfied: empyrical-reloaded>=0.5.9 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pyfolio-reloaded) (0.5.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas->vnstock) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pandas->vnstock) (2026.2)
Requirement already satisfied: tabulate>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from quantstats) (0.10.0)
Requirement already satisfied: yfinance>=0.2.40 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from quantstats) (0.2.65)
Requirement already satisfied: bottleneck>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from empyrical-reloaded>=0.5.9->pyfolio-reloaded) (1.6.0)
Requirement already satisfied: peewee<3.17.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from empyrical-reloaded>=0.5.9->pyfolio-reloaded) (3.17.3)
Requirement already satisfied: zipp>=3.20 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from importlib-metadata>=1.0->vnstock) (3.23.0)
Requirement already satisfied: decorator in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (2.18.0)
Requirement already satisfied: stack-data in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython>=3.2.3->pyfolio-reloaded) (4.9.0)
Requirement already satisfied: wcwidth in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=3.2.3->pyfolio-reloaded) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from jedi>=0.16->ipython>=3.2.3->pyfolio-reloaded) (0.8.4)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->stable-baselines3) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->stable-baselines3) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->stable-baselines3) (1.4.7)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->stable-baselines3) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->stable-baselines3) (3.1.4)
Requirement already satisfied: ptyprocess>=0.5 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pexpect>4.3->ipython>=3.2.3->pyfolio-reloaded) (0.7.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.16.0)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn>=0.16.1->pyfolio-reloaded) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn>=0.16.1->pyfolio-reloaded) (3.5.0)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from torch>=1.13->stable-baselines3) (3.14.0)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from torch>=1.13->stable-baselines3) (3.4.2)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from torch>=1.13->stable-baselines3) (3.1.6)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from torch>=1.13->stable-baselines3) (2024.10.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from torch>=1.13->stable-baselines3) (82.0.1)
Requirement already satisfied: sympy==1.13.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from torch>=1.13->stable-baselines3) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.13->stable-baselines3) (1.3.0)
Requirement already satisfied: cffi>=1.17.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnai>=2.4.8->vnstock) (2.0.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cffi>=1.17.1->vnai>=2.4.8->vnstock) (2.22)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->vnstock) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->vnstock) (3.10)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->vnstock) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->vnstock) (2026.5.20)
Requirement already satisfied: mplfinance>=0.12.9b5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from vnstock_ezchart>=1.0.1->vnstock) (0.12.10b0)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from openpyxl->vnstock) (1.1.0)
Requirement already satisfied: multitasking>=0.0.7 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from yfinance>=0.2.40->quantstats) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from yfinance>=0.2.40->quantstats) (4.3.2)
Requirement already satisfied: frozendict>=2.3.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance>=0.2.40->quantstats) (2.4.7)
Requirement already satisfied: curl_cffi>=0.7 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from yfinance>=0.2.40->quantstats) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance>=0.2.40->quantstats) (7.34.1)
Requirement already satisfied: websockets>=13.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance>=0.2.40->quantstats) (13.1)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4->vnstock) (2.6)
Requirement already satisfied: rich in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from curl_cffi>=0.7->yfinance>=0.2.40->quantstats) (13.4.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jinja2->torch>=1.13->stable-baselines3) (2.1.5)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic->vnstock) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic->vnstock) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic->vnstock) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from rich->curl_cffi>=0.7->yfinance>=0.2.40->quantstats) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance>=0.2.40->quantstats) (0.1.2)
Requirement already satisfied: executing>=1.2.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython>=3.2.3->pyfolio-reloaded) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython>=3.2.3->pyfolio-reloaded) (2.4.1)
Requirement already satisfied: pure-eval in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython>=3.2.3->pyfolio-reloaded) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [30]:
pip install stockstats

Requirement already satisfied: stockstats in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.6.8)
Requirement already satisfied: numpy>=1.16.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stockstats) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stockstats) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.24.2->stockstats) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.24.2->stockstats) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pandas>=0.24.2->stockstats) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.24.2->stockstats) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [31]:
pip install alpaca-trade-api

Requirement already satisfied: alpaca-trade-api in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.2.0)
Requirement already satisfied: pandas>=0.18.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (2.2.3)
Requirement already satisfied: numpy>=1.11.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (1.26.4)
Requirement already satisfied: requests<3,>2 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from alpaca-trade-api) (2.34.2)
Requirement already satisfied: urllib3<2,>1.24 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (1.8.0)
Collecting websockets<11,>=9.0 (from alpaca-trade-api)
  Using cached websockets-10.4-cp312-cp312-macosx_10_9_universal2.whl
Requirement already satisfied: msgpack==1.0.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (3.12.15)
Requirement already satisfied: PyYAML==6.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from alpaca-trade-api) (2.1.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from deprecation==2.1.0->alpaca-trade-api) (24.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.20.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>2->alpaca-trade-api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2023.5.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>2->alpaca-trade-api) (2026.5.20)
Requirement already satisfied: typing-extensions>=4.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiosignal>=1.4.0->aiohttp<4,>=3.8.3->alpaca-trade-api) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.18.1->alpaca-trade-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.18.1->alpaca-trade-api) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pandas>=0.18.1->alpaca-trade-api) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.16.0)
Installing collected packages: websockets
  Attempting uninstall: websockets
    Found existing installation: websockets 13.1
    Uninstalling websockets-13.1:
      Successfully uninstalled websockets-13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yfinance 0.2.65 requires websockets>=13.0, but you have websockets 10.4 which is incompatible.
Successfully installed websockets-10.4
Note: you may need to restart the kernel to use updated packages.

In [32]:
import importlib.metadata

print(importlib.metadata.version("finrl"))

0.3.7

In [33]:
pip install wrds

Requirement already satisfied: wrds in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.5.0)
Requirement already satisfied: ipython<=9.8.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from wrds) (8.27.0)
Requirement already satisfied: pandas<2.3,>=2.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from wrds) (2.2.3)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from wrds) (2.9.12)
Requirement already satisfied: sqlalchemy<2.1,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from wrds) (2.0.41)
Requirement already satisfied: decorator in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (2.18.0)
Requirement already satisfied: stack-data in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from ipython<=9.8.0->wrds) (4.9.0)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas<2.3,>=2.2->wrds) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas<2.3,>=2.2->wrds) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas<2.3,>=2.2->wrds) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pandas<2.3,>=2.2->wrds) (2026.2)
Requirement already satisfied: wcwidth in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython<=9.8.0->wrds) (0.2.13)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from sqlalchemy<2.1,>=2->wrds) (4.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from jedi>=0.16->ipython<=9.8.0->wrds) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from pexpect>4.3->ipython<=9.8.0->wrds) (0.7.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython<=9.8.0->wrds) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython<=9.8.0->wrds) (2.4.1)
Requirement already satisfied: pure-eval in /Users/buithianhdao/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython<=9.8.0->wrds) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [34]:
pip install -U websockets

Requirement already satisfied: websockets in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (10.4)
Collecting websockets
  Using cached websockets-16.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.8 kB)
Using cached websockets-16.0-cp312-cp312-macosx_11_0_arm64.whl (175 kB)
Installing collected packages: websockets
  Attempting uninstall: websockets
    Found existing installation: websockets 10.4
    Uninstalling websockets-10.4:
      Successfully uninstalled websockets-10.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
alpaca-trade-api 3.2.0 requires websockets<11,>=9.0, but you have websockets 16.0 which is incompatible.
Successfully installed websockets-16.0
Note: you may need to restart the kernel to use updated packages.

In [35]:
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split

ImportError: cannot import name 'ClientProtocol' from 'websockets.client' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/client.py)

In [4]:
import pandas as pd
df_raw = pd.read_csv('data/all_processed.csv')

In [5]:
df_raw = df_raw[['time','ticker','open','high','low','close','volume']]

In [6]:
df_raw

                      time ticker   open   high    low  close   volume
0      2021-01-04 07:00:00    FPT  25.42  25.68  25.30  25.68  2151300
1      2021-01-05 07:00:00    FPT  25.59  27.09  25.51  26.75  2332200
2      2021-01-06 07:00:00    FPT  26.92  27.13  26.58  26.62  1796000
3      2021-01-07 07:00:00    FPT  26.70  26.83  26.40  26.66  2150200
4      2021-01-08 07:00:00    FPT  26.87  27.17  26.70  27.00  2720400
...                    ...    ...    ...    ...    ...    ...      ...
13495  2026-06-02 07:00:00    PNJ  65.20  65.70  64.60  65.00   694300
13496  2026-06-03 07:00:00    PNJ  65.20  65.70  64.50  65.40   433300
13497  2026-06-04 07:00:00    PNJ  65.40  65.50  64.30  65.00   660300
13498  2026-06-05 07:00:00    PNJ  65.00  65.70  64.50  65.70   672500
13499  2026-06-08 07:00:00    PNJ  64.70  65.50  64.60  65.10  1098900

[13500 rows x 7 columns]

In [7]:
df_raw[df_raw['ticker'] == 'FPT'].tail(10)

                     time ticker   open   high    low  close    volume
1340  2026-05-26 07:00:00    FPT  72.60  73.59  72.60  73.49   5104800
1341  2026-05-27 07:00:00    FPT  73.49  74.28  72.11  72.60   9176300
1342  2026-05-28 07:00:00    FPT  72.80  73.10  71.20  71.20  10646900
1343  2026-05-29 07:00:00    FPT  71.20  72.50  70.80  71.60   5446700
1344  2026-06-01 07:00:00    FPT  72.20  73.40  72.10  72.90   5972700
1345  2026-06-02 07:00:00    FPT  73.00  75.60  73.00  74.80  17368000
1346  2026-06-03 07:00:00    FPT  75.10  77.70  75.00  76.50  25278600
1347  2026-06-04 07:00:00    FPT  76.70  77.20  75.80  76.10  11304700
1348  2026-06-05 07:00:00    FPT  76.00  76.00  74.30  75.00  11218100
1349  2026-06-08 07:00:00    FPT  73.70  74.50  72.80  72.90  10914200

In [8]:
df_raw['time'] = pd.to_datetime(df_raw['time'])
# lấy ngày của cột time làm cột date 
df_raw['date'] = df_raw['time'].dt.date
df_raw.drop(columns=['time'], inplace=True)
df_raw

      ticker   open   high    low  close   volume        date
0        FPT  25.42  25.68  25.30  25.68  2151300  2021-01-04
1        FPT  25.59  27.09  25.51  26.75  2332200  2021-01-05
2        FPT  26.92  27.13  26.58  26.62  1796000  2021-01-06
3        FPT  26.70  26.83  26.40  26.66  2150200  2021-01-07
4        FPT  26.87  27.17  26.70  27.00  2720400  2021-01-08
...      ...    ...    ...    ...    ...      ...         ...
13495    PNJ  65.20  65.70  64.60  65.00   694300  2026-06-02
13496    PNJ  65.20  65.70  64.50  65.40   433300  2026-06-03
13497    PNJ  65.40  65.50  64.30  65.00   660300  2026-06-04
13498    PNJ  65.00  65.70  64.50  65.70   672500  2026-06-05
13499    PNJ  64.70  65.50  64.60  65.10  1098900  2026-06-08

[13500 rows x 7 columns]

In [9]:
df_raw = df_raw[['date','ticker','open','high','low','close','volume']]

In [10]:
# doi ten ticker thanh tick 
df_raw.rename(columns={'ticker':'tic'}, inplace=True)

In [11]:
df_raw

             date  tic   open   high    low  close   volume
0      2021-01-04  FPT  25.42  25.68  25.30  25.68  2151300
1      2021-01-05  FPT  25.59  27.09  25.51  26.75  2332200
2      2021-01-06  FPT  26.92  27.13  26.58  26.62  1796000
3      2021-01-07  FPT  26.70  26.83  26.40  26.66  2150200
4      2021-01-08  FPT  26.87  27.17  26.70  27.00  2720400
...           ...  ...    ...    ...    ...    ...      ...
13495  2026-06-02  PNJ  65.20  65.70  64.60  65.00   694300
13496  2026-06-03  PNJ  65.20  65.70  64.50  65.40   433300
13497  2026-06-04  PNJ  65.40  65.50  64.30  65.00   660300
13498  2026-06-05  PNJ  65.00  65.70  64.50  65.70   672500
13499  2026-06-08  PNJ  64.70  65.50  64.60  65.10  1098900

[13500 rows x 7 columns]

In [12]:
INDICATORS = [
    "macd", "boll_ub", "boll_lb", "rsi_30",
    "cci_30", "dx_30", "close_30_sma", "close_60_sma"
]

In [16]:
fe = FeatureEngineer(
    use_technical_indicator=True,
    tech_indicator_list=INDICATORS,
    use_turbulence=True,          # Thêm turbulence index để đo rủi ro thị trường
    user_defined_feature=False
)

NameError: name 'FeatureEngineer' is not defined

In [37]:
df_processed = fe.preprocess_data(df_raw)

Successfully added technical indicators
Successfully added turbulence index

In [40]:
# Train/Test split
TRAIN_START, TRAIN_END = "2021-01-01", "2025-12-31"
TEST_START, TEST_END   = "2026-01-01", "2026-06-08"

In [ ]:
df_processed['date'] = pd.to_datetime(df_processed['date'])

In [43]:
df_train = data_split(df_processed, TRAIN_START, TRAIN_END)
df_test  = data_split(df_processed, TEST_START, TEST_END)

In [44]:
df_train

,tic,open,high,low,close,volume,date,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,turbulence
0,FPT,25.42,25.68,25.30,25.68,2151300,2021-01-04,0.000000,27.728209,24.701791,50.000000,0.000000,0.000000,25.680000,25.680000,0.000000
0,GAS,57.23,58.21,56.71,57.82,1362600,2021-01-04,0.000000,27.728209,24.701791,50.000000,0.000000,0.000000,57.820000,57.820000,0.000000
0,GMD,23.74,24.45,23.59,23.81,4226500,2021-01-04,0.000000,27.728209,24.701791,50.000000,0.000000,0.000000,23.810000,23.810000,0.000000
0,HPG,15.77,16.15,15.64,15.88,15832600,2021-01-04,0.000000,27.728209,24.701791,50.000000,0.000000,0.000000,15.880000,15.880000,0.000000
0,MBB,7.81,8.13,7.71,8.00,42370800,2021-01-04,0.000000,27.728209,24.701791,50.000000,0.000000,0.000000,8.000000,8.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,MWG,87.00,88.50,86.60,88.50,7753100,2025-12-30,1.630351,90.094771,78.255229,59.356396,139.038382,11.841499,82.826667,82.436667,5.160764
1245,PNJ,63.29,64.28,63.16,63.88,576600,2025-12-30,1.145238,64.508141,57.213859,61.092029,177.346076,16.181256,60.159333,59.641667,5.160764
1245,VCB,57.30,58.10,57.20,57.30,2958000,2025-12-30,-0.463420,58.863018,56.126982,43.027308,-34.624614,16.049701,57.773333,59.231667,5.160764
1245,VHM,120.00,120.60,113.00,117.50,6669000,2025-12-30,3.788279,123.579583,88.280417,57.849998,147.744111,29.324440,104.596667,105.296667,5.160764
1245,VNM,62.10,62.30,61.70,61.80,1581000,2025-12-30,0.087042,64.966421,60.353579,51.338716,-51.724138,3.432232,62.610000,60.696167,5.160764

In [45]:
tickers = ['FPT',
'VCB',
'MBB',
'HPG',
'VNM',
'MWG',
'GAS',
'VHM',
'GMD',
'PNJ']

In [92]:
df_train

,date,tic,boll_lb,boll_ub,cci_30,close,close_30_sma,close_60_sma,dx_30,high,low,macd,open,rsi_30,turbulence,volume
0,2021-01-04,FPT,-1.064797,-1.073516,-0.101043,-1.100306,-1.096464,-1.091353,-1.243197,-1.115161,-1.103375,-0.120065,-1.112746,-0.210289,-0.813083,-0.414855
1,2021-01-04,GAS,-1.064797,-1.073516,-0.101043,0.337805,0.352248,0.366462,-1.243197,0.324057,0.318676,-0.120065,0.310208,-0.210289,-0.813083,-0.487381
2,2021-01-04,GMD,-1.064797,-1.073516,-0.101043,-1.183980,-1.180754,-1.176173,-1.243197,-1.169580,-1.180793,-0.120065,-1.187898,-0.210289,-0.813083,-0.224027
3,2021-01-04,HPG,-1.064797,-1.073516,-0.101043,-1.538809,-1.538199,-1.535864,-1.243197,-1.536795,-1.540720,-0.120065,-1.544419,-0.210289,-0.813083,0.843231
4,2021-01-04,MBB,-1.064797,-1.073516,-0.101043,-1.891402,-1.893390,-1.893287,-1.243197,-1.891623,-1.899741,-0.120065,-1.900493,-0.210289,-0.813083,3.283594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12455,2025-12-30,MWG,1.473447,1.575870,1.135585,1.710589,1.479425,1.483032,-0.410938,1.664172,1.671910,1.450949,1.641908,0.842897,-0.363794,0.100267
12456,2025-12-30,PNJ,0.476160,0.488927,1.476299,0.608961,0.457694,0.449090,-0.105926,0.592611,0.610692,0.983493,0.581290,1.038265,-0.363794,-0.559659
12457,2025-12-30,VCB,0.424646,0.249118,-0.408999,0.314538,0.350145,0.430493,-0.115172,0.319191,0.340860,-0.566620,0.313340,-0.995157,-0.363794,-0.340674
12458,2025-12-30,VHM,1.948605,2.998334,1.213015,3.008200,2.460709,2.519923,0.817820,3.084367,2.867139,3.530341,3.118094,0.673332,-0.363794,0.000577
12459,2025-12-30,VNM,0.624972,0.508395,-0.561085,0.515891,0.568158,0.496920,-1.001968,0.505011,0.544592,-0.036191,0.528058,-0.059598,-0.363794,-0.467298

In [93]:
df_test

,date,tic,boll_lb,boll_ub,cci_30,close,close_30_sma,close_60_sma,dx_30,high,low,macd,open,rsi_30,turbulence,volume
0,2026-01-05,FPT,2.078621,1.823434,-0.561335,1.943711,2.003573,2.047206,-0.525328,1.925205,1.913220,-0.628622,1.972931,-0.438733,2.466024,0.033709
1,2026-01-05,GAS,0.467394,0.991177,2.025539,1.213917,0.700979,0.606181,1.869534,1.173077,1.047132,2.850675,1.020120,1.865467,2.466024,-0.119408
2,2026-01-05,GMD,0.392014,0.306446,-0.100927,0.385683,0.405422,0.532202,-0.418886,0.379803,0.404243,-0.471326,0.401911,-0.603433,2.466024,-0.554151
3,2026-01-05,HPG,-1.137146,-1.223709,-1.616765,-1.213064,-1.181460,-1.168477,-1.053722,-1.202762,-1.210221,-0.231004,-1.195950,-0.755132,2.466024,3.662189
4,2026-01-05,MBB,-1.099279,-1.158159,0.419913,-1.115072,-1.152206,-1.143855,-0.872248,-1.112064,-1.162231,0.126606,-1.115878,0.241859,2.466024,2.776702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,2026-06-05,MWG,1.313294,1.337509,-0.760299,1.240764,1.417973,1.437145,-0.030117,1.239441,1.264446,-1.374040,1.261678,-0.748984,-0.666213,-0.314577
1016,2026-06-05,PNJ,0.738560,0.710326,-0.679936,0.690398,0.776405,0.943246,0.424171,0.655436,0.671359,-1.337702,0.657783,-0.837295,-0.666213,-0.550841
1017,2026-06-05,VCB,0.573806,0.537688,-0.042705,0.511417,0.531347,0.484167,-0.535038,0.513859,0.540065,0.205971,0.541477,-0.193525,-0.666213,-0.243825
1018,2026-06-05,VHM,4.721151,4.682407,-0.373721,4.551910,4.668335,3.805603,-0.743505,4.544379,4.496997,2.007021,4.415349,0.432356,-0.666213,-0.271274
1019,2026-06-05,VNM,0.512233,0.323971,-1.028394,0.363757,0.449310,0.498153,-0.311031,0.354585,0.390661,-0.767644,0.380439,-1.069124,-0.666213,-0.441081

In [95]:
print(type(df_train))

print(df_train.head())

print(df_train.columns)

print(df_train.index)

print(df_train.groupby("date").size().head())

<class 'pandas.core.frame.DataFrame'>
        date  tic   boll_lb   boll_ub    cci_30     close  close_30_sma  \
0 2021-01-04  FPT -1.064797 -1.073516 -0.101043 -1.100306     -1.096464
1 2021-01-04  GAS -1.064797 -1.073516 -0.101043  0.337805      0.352248
2 2021-01-04  GMD -1.064797 -1.073516 -0.101043 -1.183980     -1.180754
3 2021-01-04  HPG -1.064797 -1.073516 -0.101043 -1.538809     -1.538199
4 2021-01-04  MBB -1.064797 -1.073516 -0.101043 -1.891402     -1.893390

   close_60_sma     dx_30      high       low      macd      open    rsi_30  \
0     -1.091353 -1.243197 -1.115161 -1.103375 -0.120065 -1.112746 -0.210289
1      0.366462 -1.243197  0.324057  0.318676 -0.120065  0.310208 -0.210289
2     -1.176173 -1.243197 -1.169580 -1.180793 -0.120065 -1.187898 -0.210289
3     -1.535864 -1.243197 -1.536795 -1.540720 -0.120065 -1.544419 -0.210289
4     -1.893287 -1.243197 -1.891623 -1.899741 -0.120065 -1.900493 -0.210289

   turbulence    volume
0   -0.813083 -0.414855
1   -0.813083 -0.487381
2   -0.813083 -0.224027
3   -0.813083  0.843231
4   -0.813083  3.283594
Index(['date', 'tic', 'boll_lb', 'boll_ub', 'cci_30', 'close', 'close_30_sma',
       'close_60_sma', 'dx_30', 'high', 'low', 'macd', 'open', 'rsi_30',
       'turbulence', 'volume'],
      dtype='object')
RangeIndex(start=0, stop=12460, step=1)
date
2021-01-04    10
2021-01-05    10
2021-01-06    10
2021-01-07    10
2021-01-08    10
dtype: int64

In [94]:
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent

stock_dim = len(tickers)  # = 10

env_kwargs = {
    "hmax": 100,
    "initial_amount": 1_000_000_000,
    "buy_cost_pct":  [0.0015] * stock_dim,   # ← fix: list 10 phần tử
    "sell_cost_pct": [0.0015] * stock_dim,   # ← fix: list 10 phần tử
    "reward_scaling": 1e-4,
    "state_space": 101,
    "stock_dim": stock_dim,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dim,
    "num_stock_shares": [0] * stock_dim,
    "print_verbosity": 1,
}

# ============================================================
# FIX 1: Tăng timesteps + điều chỉnh hyperparams
# ============================================================
PPO_PARAMS = {
    "n_steps": 512,          # ← giảm xuống (2048 quá lớn với 10 mã)
    "ent_coef": 0.05,        # ← tăng lên để khuyến khích exploration
    "learning_rate": 1e-4,   
    "batch_size": 64,        # ← giảm xuống
    "gamma": 0.99,
    "gae_lambda": 0.95,
}

# ============================================================
# FIX 4: Retrain với timesteps đủ lớn
# Rule of thumb: stock_dim × 50,000 timesteps tối thiểu
# 10 mã × 50,000 = 500,000
# ============================================================

# Sanity check trước khi train
e_train_gym = StockTradingEnv(df=df_train, **env_kwargs)
obs, _ = e_train_gym.reset()
action = e_train_gym.action_space.sample()
obs2, reward, done, trunc, info = e_train_gym.step(action)
print("✓ Environment OK — reward:", round(reward, 4))

# Train
env_train, _ = e_train_gym.get_sb_env()
agent = DRLAgent(env=env_train)
model_ppo = agent.get_model("ppo", model_kwargs=PPO_PARAMS)
trained_ppo = agent.train_model(model=model_ppo, tb_log_name="ppo_vn", total_timesteps=500_000)

AttributeError: 'numpy.float64' object has no attribute 'values'

In [47]:
# Chạy cell này TRƯỚC khi train để kiểm tra
print("Số tickers:", len(tickers))
print("Số indicators:", len(INDICATORS))
print("Columns trong df_train:", df_train.columns.tolist())
print("Shape df_train:", df_train.shape)

# Kiểm tra state_space tính đúng chưa
stock_dim = len(tickers)
state_space = 1 + 2 * stock_dim + len(INDICATORS) * stock_dim
print(f"\nstock_dim = {stock_dim}")
print(f"state_space = 1 + 2×{stock_dim} + {len(INDICATORS)}×{stock_dim} = {state_space}")

# Kiểm tra env_kwargs
print("\nenv_kwargs hiện tại:")
for k, v in env_kwargs.items():
    print(f"  {k}: {v}")

Số tickers: 10
Số indicators: 8
Columns trong df_train: ['tic', 'open', 'high', 'low', 'close', 'volume', 'date', 'macd', 'boll_ub', 'boll_lb', 'rsi_30', 'cci_30', 'dx_30', 'close_30_sma', 'close_60_sma', 'turbulence']
Shape df_train: (12460, 16)

stock_dim = 10
state_space = 1 + 2×10 + 8×10 = 101

env_kwargs hiện tại:
  hmax: 100
  initial_amount: 1000000000
  buy_cost_pct: 0.0015
  sell_cost_pct: 0.0015
  reward_scaling: 0.0001
  state_space: 101
  stock_dim: 10
  tech_indicator_list: ['macd', 'boll_ub', 'boll_lb', 'rsi_30', 'cci_30', 'dx_30', 'close_30_sma', 'close_60_sma']
  action_space: 10
  num_stock_shares: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [85]:
from finrl.plot import backtest_stats

# account_value đang bị scale sai → nhân ngược lại
# initial_amount = 1_000_000_000, reward_scaling = 1e-4
df_account_plot = df_account_ppo.copy()
df_account_plot["account_value"] = df_account_plot["account_value"] * (1 / 1e-4)

print("Kiểm tra account_value sau rescale:")
print(df_account_plot["account_value"].describe())
print(f"Giá trị đầu:  {df_account_plot['account_value'].iloc[0]:,.0f} VNĐ")
print(f"Giá trị cuối: {df_account_plot['account_value'].iloc[-1]:,.0f} VNĐ")

print("=" * 50)
print("PPO Agent Performance (sau rescale)")
print("=" * 50)
perf_stats = backtest_stats(account_value=df_account_plot)

Kiểm tra account_value sau rescale:
count    1.020000e+02
mean     1.000001e+13
std      1.940689e+08
min      9.999562e+12
25%      9.999891e+12
50%      1.000000e+13
75%      1.000015e+13
max      1.000047e+13
Name: account_value, dtype: float64
Giá trị đầu:  10,000,000,000,000 VNĐ
Giá trị cuối: 10,000,131,121,492 VNĐ
==================================================
PPO Agent Performance (sau rescale)
==================================================
Annual return          0.000032
Cumulative returns     0.000013
Annual volatility      0.000121
Sharpe ratio           0.271124
Calmar ratio           0.708278
Stability              0.230111
Max drawdown          -0.000046
Omega ratio            1.049517
Sortino ratio          0.412400
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.925147
Daily value at risk   -0.000015
dtype: float64

In [86]:
# Kiểm tra agent có thực sự giao dịch không
print("Actions của agent (5 ngày đầu):")
print(df_actions_ppo.head())

print("\nSố ngày có giao dịch:")
action_cols = [c for c in df_actions_ppo.columns if c != "date"]
active_days = (df_actions_ppo[action_cols].abs() > 0.01).any(axis=1).sum()
print(f"{active_days} / {len(df_actions_ppo)} ngày")

print("\nPhân phối action:")
print(df_actions_ppo[action_cols].describe())

Actions của agent (5 ngày đầu):
            FPT  GAS  GMD  HPG  MBB  MWG  PNJ  VCB  VHM  VNM
date
2026-01-05   13    0    0    3   66    0   30    0   20    0
2026-01-06   13    0    0    3   66    0   30    0   20    0
2026-01-07   13    0    0    3   66    0   30    0   20    0
2026-01-08   13    0    0    3   66    0   30    0   20    0
2026-01-09   13    0    0    3   66    0   30    0   20    0

Số ngày có giao dịch:
101 / 101 ngày

Phân phối action:
         FPT    GAS    GMD    HPG    MBB    MWG    PNJ    VCB    VHM    VNM
count  101.0  101.0  101.0  101.0  101.0  101.0  101.0  101.0  101.0  101.0
mean    13.0    0.0    0.0    3.0   66.0    0.0   30.0    0.0   20.0    0.0
std      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
min     13.0    0.0    0.0    3.0   66.0    0.0   30.0    0.0   20.0    0.0
25%     13.0    0.0    0.0    3.0   66.0    0.0   30.0    0.0   20.0    0.0
50%     13.0    0.0    0.0    3.0   66.0    0.0   30.0    0.0   20.0    0.0
75%     13.0    0.0    0.0    3.0   66.0    0.0   30.0    0.0   20.0    0.0
max     13.0    0.0    0.0    3.0   66.0    0.0   30.0    0.0   20.0    0.0